// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk/stream/market_update_v1/request.proto

#include "sdk/stream/market_update_v1/request.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace kaikosdk {
constexpr StreamMarketUpdateRequestV1::StreamMarketUpdateRequestV1(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : commodities_()
  , _commodities_cached_byte_size_(0)
  , instrument_criteria_(nullptr)
  , interval_(nullptr)
  , snapshot_type_(0)
{}
struct StreamMarketUpdateRequestV1DefaultTypeInternal {
  constexpr StreamMarketUpdateRequestV1DefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~StreamMarketUpdateRequestV1DefaultTypeInternal() {}
  union {
    StreamMarketUpdateRequestV1 _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT StreamMarketUpdateRequestV1DefaultTypeInternal _StreamMarketUpdateRequestV1_default_instance_;
}  // namespace kaikosdk
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_sdk_2fstream_2fmarket_5fupdate_5fv1_2frequest_2eproto[1];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_sdk_2fstream_2fmarket_5fupdate_5fv1_2frequest_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_sdk_2fstream_2fmarket_5fupdate_5fv1_2frequest_2eproto = nullptr;

const uint32_t TableStruct_sdk_2fstream_2fmarket_5fupdate_5fv1_2frequest_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::kaikosdk::StreamMarketUpdateRequestV1, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::kaikosdk::StreamMarketUpdateRequestV1, instrument_criteria_),
  PROTOBUF_FIELD_OFFSET(::kaikosdk::StreamMarketUpdateRequestV1, commodities_),
  PROTOBUF_FIELD_OFFSET(::kaikosdk::StreamMarketUpdateRequestV1, interval_),
  PROTOBUF_FIELD_OFFSET(::kaikosdk::StreamMarketUpdateRequestV1, snapshot_type_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::kaikosdk::StreamMarketUpdateRequestV1)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::kaikosdk::_StreamMarketUpdateRequestV1_default_instance_),
};

const char descriptor_table_protodef_sdk_2fstream_2fmarket_5fupdate_5fv1_2frequest_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n)sdk/stream/market_update_v1/request.pr"
  "oto\022\010kaikosdk\032\034sdk/core/data_interval.pr"
  "oto\032\"sdk/core/instrument_criteria.proto\032"
  "+sdk/stream/market_update_v1/commodity.p"
  "roto\"\323\002\n\033StreamMarketUpdateRequestV1\0229\n\023"
  "instrument_criteria\030\001 \001(\0132\034.kaikosdk.Ins"
  "trumentCriteria\022:\n\013commodities\030\002 \003(\0162%.k"
  "aikosdk.StreamMarketUpdateCommodity\022(\n\010i"
  "nterval\030\003 \001(\0132\026.kaikosdk.DataInterval\022R\n"
  "\rsnapshot_type\030\004 \001(\0162;.kaikosdk.StreamMa"
  "rketUpdateRequestV1.OrderbookSnapshotTyp"
  "e\"\?\n\025OrderbookSnapshotType\022\013\n\007UNKNOWN\020\000\022"
  "\017\n\013TEN_PERCENT\020\001\022\010\n\004FULL\020\002B\233\001\n%com.kaiko"
  ".sdk.stream.market_update_v1P\001ZOgithub.c"
  "om/challengerdeep/kaiko-go-sdk/stream/ma"
  "rket_update_v1;market_update_v1\252\002\036KaikoS"
  "dk.Stream.MarketUpdateV1b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_sdk_2fstream_2fmarket_5fupdate_5fv1_2frequest_2eproto_deps[3] = {
  &::descriptor_table_sdk_2fcore_2fdata_5finterval_2eproto,
  &::descriptor_table_sdk_2fcore_2finstrument_5fcriteria_2eproto,
  &::descriptor_table_sdk_2fstream_2fmarket_5fupdate_5fv1_2fcommodity_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_sdk_2fstream_2fmarket_5fupdate_5fv1_2frequest_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_sdk_2fstream_2fmarket_5fupdate_5fv1_2frequest_2eproto = {
  false, false, 672, descriptor_table_protodef_sdk_2fstream_2fmarket_5fupdate_5fv1_2frequest_2eproto, "sdk/stream/market_update_v1/request.proto", 
  &descriptor_table_sdk_2fstream_2fmarket_5fupdate_5fv1_2frequest_2eproto_once, descriptor_table_sdk_2fstream_2fmarket_5fupdate_5fv1_2frequest_2eproto_deps, 3, 1,
  schemas, file_default_instances, TableStruct_sdk_2fstream_2fmarket_5fupdate_5fv1_2frequest_2eproto::offsets,
  file_level_metadata_sdk_2fstream_2fmarket_5fupdate_5fv1_2frequest_2eproto, file_level_enum_descriptors_sdk_2fstream_2fmarket_5fupdate_5fv1_2frequest_2eproto, file_level_service_descriptors_sdk_2fstream_2fmarket_5fupdate_5fv1_2frequest_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_sdk_2fstream_2fmarket_5fupdate_5fv1_2frequest_2eproto_getter() {
  return &descriptor_table_sdk_2fstream_2fmarket_5fupdate_5fv1_2frequest_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_sdk_2fstream_2fmarket_5fupdate_5fv1_2frequest_2eproto(&descriptor_table_sdk_2fstream_2fmarket_5fupdate_5fv1_2frequest_2eproto);
namespace kaikosdk {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* StreamMarketUpdateRequestV1_OrderbookSnapshotType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_sdk_2fstream_2fmarket_5fupdate_5fv1_2frequest_2eproto);
  return file_level_enum_descriptors_sdk_2fstream_2fmarket_5fupdate_5fv1_2frequest_2eproto[0];
}
bool StreamMarketUpdateRequestV1_OrderbookSnapshotType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr StreamMarketUpdateRequestV1_OrderbookSnapshotType StreamMarketUpdateRequestV1::UNKNOWN;
constexpr StreamMarketUpdateRequestV1_OrderbookSnapshotType StreamMarketUpdateRequestV1::TEN_PERCENT;
constexpr StreamMarketUpdateRequestV1_OrderbookSnapshotType StreamMarketUpdateRequestV1::FULL;
constexpr StreamMarketUpdateRequestV1_OrderbookSnapshotType StreamMarketUpdateRequestV1::OrderbookSnapshotType_MIN;
constexpr StreamMarketUpdateRequestV1_OrderbookSnapshotType StreamMarketUpdateRequestV1::OrderbookSnapshotType_MAX;
constexpr int StreamMarketUpdateRequestV1::OrderbookSnapshotType_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

// ===================================================================

class StreamMarketUpdateRequestV1::_Internal {
 public:
  static const ::kaikosdk::InstrumentCriteria& instrument_criteria(const StreamMarketUpdateRequestV1* msg);
  static const ::kaikosdk::DataInterval& interval(const StreamMarketUpdateRequestV1* msg);
};

const ::kaikosdk::InstrumentCriteria&
StreamMarketUpdateRequestV1::_Internal::instrument_criteria(const StreamMarketUpdateRequestV1* msg) {
  return *msg->instrument_criteria_;
}
const ::kaikosdk::DataInterval&
StreamMarketUpdateRequestV1::_Internal::interval(const StreamMarketUpdateRequestV1* msg) {
  return *msg->interval_;
}
void StreamMarketUpdateRequestV1::clear_instrument_criteria() {
  if (GetArenaForAllocation() == nullptr && instrument_criteria_ != nullptr) {
    delete instrument_criteria_;
  }
  instrument_criteria_ = nullptr;
}
void StreamMarketUpdateRequestV1::clear_interval() {
  if (GetArenaForAllocation() == nullptr && interval_ != nullptr) {
    delete interval_;
  }
  interval_ = nullptr;
}
StreamMarketUpdateRequestV1::StreamMarketUpdateRequestV1(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  commodities_(arena) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:kaikosdk.StreamMarketUpdateRequestV1)
}
StreamMarketUpdateRequestV1::StreamMarketUpdateRequestV1(const StreamMarketUpdateRequestV1& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      commodities_(from.commodities_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_instrument_criteria()) {
    instrument_criteria_ = new ::kaikosdk::InstrumentCriteria(*from.instrument_criteria_);
  } else {
    instrument_criteria_ = nullptr;
  }
  if (from._internal_has_interval()) {
    interval_ = new ::kaikosdk::DataInterval(*from.interval_);
  } else {
    interval_ = nullptr;
  }
  snapshot_type_ = from.snapshot_type_;
  // @@protoc_insertion_point(copy_constructor:kaikosdk.StreamMarketUpdateRequestV1)
}

inline void StreamMarketUpdateRequestV1::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&instrument_criteria_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&snapshot_type_) -
    reinterpret_cast<char*>(&instrument_criteria_)) + sizeof(snapshot_type_));
}

StreamMarketUpdateRequestV1::~StreamMarketUpdateRequestV1() {
  // @@protoc_insertion_point(destructor:kaikosdk.StreamMarketUpdateRequestV1)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void StreamMarketUpdateRequestV1::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete instrument_criteria_;
  if (this != internal_default_instance()) delete interval_;
}

void StreamMarketUpdateRequestV1::ArenaDtor(void* object) {
  StreamMarketUpdateRequestV1* _this = reinterpret_cast< StreamMarketUpdateRequestV1* >(object);
  (void)_this;
}
void StreamMarketUpdateRequestV1::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void StreamMarketUpdateRequestV1::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void StreamMarketUpdateRequestV1::Clear() {
// @@protoc_insertion_point(message_clear_start:kaikosdk.StreamMarketUpdateRequestV1)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  commodities_.Clear();
  if (GetArenaForAllocation() == nullptr && instrument_criteria_ != nullptr) {
    delete instrument_criteria_;
  }
  instrument_criteria_ = nullptr;
  if (GetArenaForAllocation() == nullptr && interval_ != nullptr) {
    delete interval_;
  }
  interval_ = nullptr;
  snapshot_type_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* StreamMarketUpdateRequestV1::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .kaikosdk.InstrumentCriteria instrument_criteria = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_instrument_criteria(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .kaikosdk.StreamMarketUpdateCommodity commodities = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedEnumParser(_internal_mutable_commodities(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 16) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_add_commodities(static_cast<::kaikosdk::StreamMarketUpdateCommodity>(val));
        } else
          goto handle_unusual;
        continue;
      // .kaikosdk.DataInterval interval = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_interval(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .kaikosdk.StreamMarketUpdateRequestV1.OrderbookSnapshotType snapshot_type = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_snapshot_type(static_cast<::kaikosdk::StreamMarketUpdateRequestV1_OrderbookSnapshotType>(val));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* StreamMarketUpdateRequestV1::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:kaikosdk.StreamMarketUpdateRequestV1)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .kaikosdk.InstrumentCriteria instrument_criteria = 1;
  if (this->_internal_has_instrument_criteria()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::instrument_criteria(this), target, stream);
  }

  // repeated .kaikosdk.StreamMarketUpdateCommodity commodities = 2;
  {
    int byte_size = _commodities_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteEnumPacked(
          2, commodities_, byte_size, target);
    }
  }

  // .kaikosdk.DataInterval interval = 3;
  if (this->_internal_has_interval()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        3, _Internal::interval(this), target, stream);
  }

  // .kaikosdk.StreamMarketUpdateRequestV1.OrderbookSnapshotType snapshot_type = 4;
  if (this->_internal_snapshot_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      4, this->_internal_snapshot_type(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:kaikosdk.StreamMarketUpdateRequestV1)
  return target;
}

size_t StreamMarketUpdateRequestV1::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:kaikosdk.StreamMarketUpdateRequestV1)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .kaikosdk.StreamMarketUpdateCommodity commodities = 2;
  {
    size_t data_size = 0;
    unsigned int count = static_cast<unsigned int>(this->_internal_commodities_size());for (unsigned int i = 0; i < count; i++) {
      data_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(
        this->_internal_commodities(static_cast<int>(i)));
    }
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<int32_t>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _commodities_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // .kaikosdk.InstrumentCriteria instrument_criteria = 1;
  if (this->_internal_has_instrument_criteria()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *instrument_criteria_);
  }

  // .kaikosdk.DataInterval interval = 3;
  if (this->_internal_has_interval()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *interval_);
  }

  // .kaikosdk.StreamMarketUpdateRequestV1.OrderbookSnapshotType snapshot_type = 4;
  if (this->_internal_snapshot_type() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_snapshot_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData StreamMarketUpdateRequestV1::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    StreamMarketUpdateRequestV1::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*StreamMarketUpdateRequestV1::GetClassData() const { return &_class_data_; }

void StreamMarketUpdateRequestV1::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<StreamMarketUpdateRequestV1 *>(to)->MergeFrom(
      static_cast<const StreamMarketUpdateRequestV1 &>(from));
}


void StreamMarketUpdateRequestV1::MergeFrom(const StreamMarketUpdateRequestV1& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:kaikosdk.StreamMarketUpdateRequestV1)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  commodities_.MergeFrom(from.commodities_);
  if (from._internal_has_instrument_criteria()) {
    _internal_mutable_instrument_criteria()->::kaikosdk::InstrumentCriteria::MergeFrom(from._internal_instrument_criteria());
  }
  if (from._internal_has_interval()) {
    _internal_mutable_interval()->::kaikosdk::DataInterval::MergeFrom(from._internal_interval());
  }
  if (from._internal_snapshot_type() != 0) {
    _internal_set_snapshot_type(from._internal_snapshot_type());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void StreamMarketUpdateRequestV1::CopyFrom(const StreamMarketUpdateRequestV1& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:kaikosdk.StreamMarketUpdateRequestV1)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StreamMarketUpdateRequestV1::IsInitialized() const {
  return true;
}

void StreamMarketUpdateRequestV1::InternalSwap(StreamMarketUpdateRequestV1* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  commodities_.InternalSwap(&other->commodities_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(StreamMarketUpdateRequestV1, snapshot_type_)
      + sizeof(StreamMarketUpdateRequestV1::snapshot_type_)
      - PROTOBUF_FIELD_OFFSET(StreamMarketUpdateRequestV1, instrument_criteria_)>(
          reinterpret_cast<char*>(&instrument_criteria_),
          reinterpret_cast<char*>(&other->instrument_criteria_));
}

::PROTOBUF_NAMESPACE_ID::Metadata StreamMarketUpdateRequestV1::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_sdk_2fstream_2fmarket_5fupdate_5fv1_2frequest_2eproto_getter, &descriptor_table_sdk_2fstream_2fmarket_5fupdate_5fv1_2frequest_2eproto_once,
      file_level_metadata_sdk_2fstream_2fmarket_5fupdate_5fv1_2frequest_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace kaikosdk
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::kaikosdk::StreamMarketUpdateRequestV1* Arena::CreateMaybeMessage< ::kaikosdk::StreamMarketUpdateRequestV1 >(Arena* arena) {
  return Arena::CreateMessageInternal< ::kaikosdk::StreamMarketUpdateRequestV1 >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
