// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk/stream/evm_oracle_v1/request.proto

#include "sdk/stream/evm_oracle_v1/request.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace kaikosdk {
PROTOBUF_CONSTEXPR StreamEvmOracleServiceRequestV1::StreamEvmOracleServiceRequestV1(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.instrument_ids_)*/{}
  , /*decltype(_impl_.blockchain_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct StreamEvmOracleServiceRequestV1DefaultTypeInternal {
  PROTOBUF_CONSTEXPR StreamEvmOracleServiceRequestV1DefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~StreamEvmOracleServiceRequestV1DefaultTypeInternal() {}
  union {
    StreamEvmOracleServiceRequestV1 _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StreamEvmOracleServiceRequestV1DefaultTypeInternal _StreamEvmOracleServiceRequestV1_default_instance_;
}  // namespace kaikosdk
static ::_pb::Metadata file_level_metadata_sdk_2fstream_2fevm_5foracle_5fv1_2frequest_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_sdk_2fstream_2fevm_5foracle_5fv1_2frequest_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_sdk_2fstream_2fevm_5foracle_5fv1_2frequest_2eproto = nullptr;

const uint32_t TableStruct_sdk_2fstream_2fevm_5foracle_5fv1_2frequest_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::kaikosdk::StreamEvmOracleServiceRequestV1, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::kaikosdk::StreamEvmOracleServiceRequestV1, _impl_.instrument_ids_),
  PROTOBUF_FIELD_OFFSET(::kaikosdk::StreamEvmOracleServiceRequestV1, _impl_.blockchain_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::kaikosdk::StreamEvmOracleServiceRequestV1)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::kaikosdk::_StreamEvmOracleServiceRequestV1_default_instance_._instance,
};

const char descriptor_table_protodef_sdk_2fstream_2fevm_5foracle_5fv1_2frequest_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n&sdk/stream/evm_oracle_v1/request.proto"
  "\022\010kaikosdk\"M\n\037StreamEvmOracleServiceRequ"
  "estV1\022\026\n\016instrument_ids\030\001 \003(\t\022\022\n\nblockch"
  "ain\030\002 \001(\tB\212\001\n\"com.kaiko.sdk.stream.evm_o"
  "racle_v1P\001ZDgithub.com/kaikodata/kaiko-g"
  "o-sdk/stream/evm_oracle_v1;evm_oracle_v1"
  "\252\002\033KaikoSdk.Stream.EvmOracleV1b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_sdk_2fstream_2fevm_5foracle_5fv1_2frequest_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_sdk_2fstream_2fevm_5foracle_5fv1_2frequest_2eproto = {
    false, false, 278, descriptor_table_protodef_sdk_2fstream_2fevm_5foracle_5fv1_2frequest_2eproto,
    "sdk/stream/evm_oracle_v1/request.proto",
    &descriptor_table_sdk_2fstream_2fevm_5foracle_5fv1_2frequest_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_sdk_2fstream_2fevm_5foracle_5fv1_2frequest_2eproto::offsets,
    file_level_metadata_sdk_2fstream_2fevm_5foracle_5fv1_2frequest_2eproto, file_level_enum_descriptors_sdk_2fstream_2fevm_5foracle_5fv1_2frequest_2eproto,
    file_level_service_descriptors_sdk_2fstream_2fevm_5foracle_5fv1_2frequest_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_sdk_2fstream_2fevm_5foracle_5fv1_2frequest_2eproto_getter() {
  return &descriptor_table_sdk_2fstream_2fevm_5foracle_5fv1_2frequest_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_sdk_2fstream_2fevm_5foracle_5fv1_2frequest_2eproto(&descriptor_table_sdk_2fstream_2fevm_5foracle_5fv1_2frequest_2eproto);
namespace kaikosdk {

// ===================================================================

class StreamEvmOracleServiceRequestV1::_Internal {
 public:
};

StreamEvmOracleServiceRequestV1::StreamEvmOracleServiceRequestV1(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:kaikosdk.StreamEvmOracleServiceRequestV1)
}
StreamEvmOracleServiceRequestV1::StreamEvmOracleServiceRequestV1(const StreamEvmOracleServiceRequestV1& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  StreamEvmOracleServiceRequestV1* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.instrument_ids_){from._impl_.instrument_ids_}
    , decltype(_impl_.blockchain_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.blockchain_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.blockchain_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_blockchain().empty()) {
    _this->_impl_.blockchain_.Set(from._internal_blockchain(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:kaikosdk.StreamEvmOracleServiceRequestV1)
}

inline void StreamEvmOracleServiceRequestV1::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.instrument_ids_){arena}
    , decltype(_impl_.blockchain_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.blockchain_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.blockchain_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

StreamEvmOracleServiceRequestV1::~StreamEvmOracleServiceRequestV1() {
  // @@protoc_insertion_point(destructor:kaikosdk.StreamEvmOracleServiceRequestV1)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void StreamEvmOracleServiceRequestV1::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.instrument_ids_.~RepeatedPtrField();
  _impl_.blockchain_.Destroy();
}

void StreamEvmOracleServiceRequestV1::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void StreamEvmOracleServiceRequestV1::Clear() {
// @@protoc_insertion_point(message_clear_start:kaikosdk.StreamEvmOracleServiceRequestV1)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.instrument_ids_.Clear();
  _impl_.blockchain_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* StreamEvmOracleServiceRequestV1::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated string instrument_ids = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_instrument_ids();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "kaikosdk.StreamEvmOracleServiceRequestV1.instrument_ids"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      // string blockchain = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_blockchain();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "kaikosdk.StreamEvmOracleServiceRequestV1.blockchain"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* StreamEvmOracleServiceRequestV1::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:kaikosdk.StreamEvmOracleServiceRequestV1)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string instrument_ids = 1;
  for (int i = 0, n = this->_internal_instrument_ids_size(); i < n; i++) {
    const auto& s = this->_internal_instrument_ids(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "kaikosdk.StreamEvmOracleServiceRequestV1.instrument_ids");
    target = stream->WriteString(1, s, target);
  }

  // string blockchain = 2;
  if (!this->_internal_blockchain().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_blockchain().data(), static_cast<int>(this->_internal_blockchain().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "kaikosdk.StreamEvmOracleServiceRequestV1.blockchain");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_blockchain(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:kaikosdk.StreamEvmOracleServiceRequestV1)
  return target;
}

size_t StreamEvmOracleServiceRequestV1::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:kaikosdk.StreamEvmOracleServiceRequestV1)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string instrument_ids = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.instrument_ids_.size());
  for (int i = 0, n = _impl_.instrument_ids_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.instrument_ids_.Get(i));
  }

  // string blockchain = 2;
  if (!this->_internal_blockchain().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_blockchain());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData StreamEvmOracleServiceRequestV1::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    StreamEvmOracleServiceRequestV1::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*StreamEvmOracleServiceRequestV1::GetClassData() const { return &_class_data_; }


void StreamEvmOracleServiceRequestV1::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<StreamEvmOracleServiceRequestV1*>(&to_msg);
  auto& from = static_cast<const StreamEvmOracleServiceRequestV1&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:kaikosdk.StreamEvmOracleServiceRequestV1)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.instrument_ids_.MergeFrom(from._impl_.instrument_ids_);
  if (!from._internal_blockchain().empty()) {
    _this->_internal_set_blockchain(from._internal_blockchain());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void StreamEvmOracleServiceRequestV1::CopyFrom(const StreamEvmOracleServiceRequestV1& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:kaikosdk.StreamEvmOracleServiceRequestV1)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StreamEvmOracleServiceRequestV1::IsInitialized() const {
  return true;
}

void StreamEvmOracleServiceRequestV1::InternalSwap(StreamEvmOracleServiceRequestV1* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.instrument_ids_.InternalSwap(&other->_impl_.instrument_ids_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.blockchain_, lhs_arena,
      &other->_impl_.blockchain_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata StreamEvmOracleServiceRequestV1::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_sdk_2fstream_2fevm_5foracle_5fv1_2frequest_2eproto_getter, &descriptor_table_sdk_2fstream_2fevm_5foracle_5fv1_2frequest_2eproto_once,
      file_level_metadata_sdk_2fstream_2fevm_5foracle_5fv1_2frequest_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace kaikosdk
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::kaikosdk::StreamEvmOracleServiceRequestV1*
Arena::CreateMaybeMessage< ::kaikosdk::StreamEvmOracleServiceRequestV1 >(Arena* arena) {
  return Arena::CreateMessageInternal< ::kaikosdk::StreamEvmOracleServiceRequestV1 >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
