// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk/sdk.proto

#include "sdk/sdk.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace kaikosdk {
}  // namespace kaikosdk
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_sdk_2fsdk_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_sdk_2fsdk_2eproto = nullptr;
const uint32_t TableStruct_sdk_2fsdk_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_sdk_2fsdk_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\rsdk/sdk.proto\022\010kaikosdk\032,sdk/stream/ag"
  "gregated_price_v1/request.proto\032-sdk/str"
  "eam/aggregated_price_v1/response.proto\032,"
  "sdk/stream/aggregated_quote_v2/request.p"
  "roto\032-sdk/stream/aggregated_quote_v2/res"
  "ponse.proto\032;sdk/stream/aggregates_direc"
  "t_exchange_rate_v2/request.proto\032<sdk/st"
  "ream/aggregates_direct_exchange_rate_v2/"
  "response.proto\032,sdk/stream/aggregates_oh"
  "lcv_v1/request.proto\032-sdk/stream/aggrega"
  "tes_ohlcv_v1/response.proto\0329sdk/stream/"
  "aggregates_spot_exchange_rate_v2/request"
  ".proto\032:sdk/stream/aggregates_spot_excha"
  "nge_rate_v2/response.proto\032+sdk/stream/a"
  "ggregates_vwap_v1/request.proto\032,sdk/str"
  "eam/aggregates_vwap_v1/response.proto\032:s"
  "dk/stream/derivatives_instrument_metrics"
  "_v1/request.proto\032;sdk/stream/derivative"
  "s_instrument_metrics_v1/response.proto\032*"
  "sdk/stream/exotic_indices_v1/request.pro"
  "to\032+sdk/stream/exotic_indices_v1/respons"
  "e.proto\032,sdk/stream/index_forex_rate_v1/"
  "request.proto\032-sdk/stream/index_forex_ra"
  "te_v1/response.proto\032.sdk/stream/index_m"
  "ulti_assets_v1/request.proto\032/sdk/stream"
  "/index_multi_assets_v1/response.proto\032!s"
  "dk/stream/index_v1/request.proto\032\"sdk/st"
  "ream/index_v1/response.proto\032-sdk/stream"
  "/iv_svi_parameters_v1/request.proto\032.sdk"
  "/stream/iv_svi_parameters_v1/response.pr"
  "oto\032)sdk/stream/market_update_v1/request"
  ".proto\032*sdk/stream/market_update_v1/resp"
  "onse.proto\032\'sdk/stream/orderbookl2_v1/re"
  "quest.proto\032(sdk/stream/orderbookl2_v1/r"
  "esponse.proto\032\"sdk/stream/trades_v1/requ"
  "est.proto\032#sdk/stream/trades_v1/response"
  ".proto\0322sdk/stream/aggregated_state_pric"
  "e_v1/request.proto\0323sdk/stream/aggregate"
  "d_state_price_v1/response.proto\0325sdk/str"
  "eam/constant_duration_indices_v1/request"
  ".proto\0326sdk/stream/constant_duration_ind"
  "ices_v1/response.proto\032-sdk/stream/compo"
  "site_indices_v1/request.proto\032.sdk/strea"
  "m/composite_indices_v1/response.proto2\206\001"
  "\n\036StreamAggregatedQuoteServiceV2\022d\n\tSubs"
  "cribe\022(.kaikosdk.StreamAggregatedQuoteRe"
  "questV2\032).kaikosdk.StreamAggregatedQuote"
  "ResponseV2\"\0000\0012\211\001\n\036StreamAggregatedPrice"
  "ServiceV1\022g\n\tSubscribe\022(.kaikosdk.Stream"
  "AggregatedPriceRequestV1\032).kaikosdk.Stre"
  "amAggregatedPriceResponseV1\"\003\210\002\0010\0012\206\001\n\036S"
  "treamAggregatesOHLCVServiceV1\022d\n\tSubscri"
  "be\022(.kaikosdk.StreamAggregatesOHLCVReque"
  "stV1\032).kaikosdk.StreamAggregatesOHLCVRes"
  "ponseV1\"\0000\0012k\n\025StreamTradesServiceV1\022R\n\t"
  "Subscribe\022\037.kaikosdk.StreamTradesRequest"
  "V1\032 .kaikosdk.StreamTradesResponseV1\"\0000\001"
  "2\203\001\n\035StreamAggregatesVWAPServiceV1\022b\n\tSu"
  "bscribe\022\'.kaikosdk.StreamAggregatesVWAPR"
  "equestV1\032(.kaikosdk.StreamAggregatesVWAP"
  "ResponseV1\"\0000\0012v\n\024StreamIndexServiceV1\022^"
  "\n\tSubscribe\022%.kaikosdk.StreamIndexServic"
  "eRequestV1\032&.kaikosdk.StreamIndexService"
  "ResponseV1\"\0000\0012\227\001\n\037StreamIndexMultiAsset"
  "sServiceV1\022t\n\tSubscribe\0220.kaikosdk.Strea"
  "mIndexMultiAssetsServiceRequestV1\0321.kaik"
  "osdk.StreamIndexMultiAssetsServiceRespon"
  "seV1\"\0000\0012}\n\033StreamMarketUpdateServiceV1\022"
  "^\n\tSubscribe\022%.kaikosdk.StreamMarketUpda"
  "teRequestV1\032&.kaikosdk.StreamMarketUpdat"
  "eResponseV1\"\0000\0012\255\001\n+StreamAggregatesSpot"
  "ExchangeRateV2ServiceV1\022~\n\tSubscribe\0225.k"
  "aikosdk.StreamAggregatesSpotExchangeRate"
  "V2RequestV1\0326.kaikosdk.StreamAggregatesS"
  "potExchangeRateV2ResponseV1\"\0000\0012\270\001\n1Stre"
  "amAggregatesSpotDirectExchangeRateV2Serv"
  "iceV1\022\202\001\n\tSubscribe\0227.kaikosdk.StreamAgg"
  "regatesDirectExchangeRateV2RequestV1\0328.k"
  "aikosdk.StreamAggregatesDirectExchangeRa"
  "teV2ResponseV1\"\0000\0012\221\001\n\035StreamIndexForexR"
  "ateServiceV1\022p\n\tSubscribe\022..kaikosdk.Str"
  "eamIndexForexRateServiceRequestV1\032/.kaik"
  "osdk.StreamIndexForexRateServiceResponse"
  "V1\"\0000\0012\255\001\n+StreamDerivativesInstrumentMe"
  "tricsServiceV1\022~\n\tSubscribe\0225.kaikosdk.S"
  "treamDerivativesInstrumentMetricsRequest"
  "V1\0326.kaikosdk.StreamDerivativesInstrumen"
  "tMetricsResponseV1\"\0000\0012\206\001\n\036StreamIvSviPa"
  "rametersServiceV1\022d\n\tSubscribe\022(.kaikosd"
  "k.StreamIvSviParametersRequestV1\032).kaiko"
  "sdk.StreamIvSviParametersResponseV1\"\0000\0012"
  "\216\001\n\034StreamExoticIndicesServiceV1\022n\n\tSubs"
  "cribe\022-.kaikosdk.StreamExoticIndicesServ"
  "iceRequestV1\032..kaikosdk.StreamExoticIndi"
  "cesServiceResponseV1\"\0000\0012z\n\032StreamOrderb"
  "ookL2ServiceV1\022\\\n\tSubscribe\022$.kaikosdk.S"
  "treamOrderBookL2RequestV1\032%.kaikosdk.Str"
  "eamOrderBookL2ResponseV1\"\0000\0012\225\001\n#StreamA"
  "ggregatedStatePriceServiceV1\022n\n\tSubscrib"
  "e\022-.kaikosdk.StreamAggregatedStatePriceR"
  "equestV1\032..kaikosdk.StreamAggregatedStat"
  "ePriceResponseV1\"\0000\0012\206\001\n StreamOrderbook"
  "L2ReplayServiceV1\022b\n\tSubscribe\022*.kaikosd"
  "k.StreamOrderBookL2ReplayRequestV1\032%.kai"
  "kosdk.StreamOrderBookL2ResponseV1\"\0000\0012\255\001"
  "\n&StreamConstantDurationIndicesServiceV1"
  "\022\202\001\n\tSubscribe\0227.kaikosdk.StreamConstant"
  "DurationIndicesServiceRequestV1\0328.kaikos"
  "dk.StreamConstantDurationIndicesServiceR"
  "esponseV1\"\0000\0012\227\001\n\037StreamCompositeIndices"
  "ServiceV1\022t\n\tSubscribe\0220.kaikosdk.Stream"
  "CompositeIndicesServiceRequestV1\0321.kaiko"
  "sdk.StreamCompositeIndicesServiceRespons"
  "eV1\"\0000\001BR\n\rcom.kaiko.sdkB\010SdkProtoP\001Z*gi"
  "thub.com/kaikodata/kaiko-go-sdk;kaikosdk"
  "\252\002\010KaikoSdkb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_sdk_2fsdk_2eproto_deps[36] = {
  &::descriptor_table_sdk_2fstream_2faggregated_5fprice_5fv1_2frequest_2eproto,
  &::descriptor_table_sdk_2fstream_2faggregated_5fprice_5fv1_2fresponse_2eproto,
  &::descriptor_table_sdk_2fstream_2faggregated_5fquote_5fv2_2frequest_2eproto,
  &::descriptor_table_sdk_2fstream_2faggregated_5fquote_5fv2_2fresponse_2eproto,
  &::descriptor_table_sdk_2fstream_2faggregated_5fstate_5fprice_5fv1_2frequest_2eproto,
  &::descriptor_table_sdk_2fstream_2faggregated_5fstate_5fprice_5fv1_2fresponse_2eproto,
  &::descriptor_table_sdk_2fstream_2faggregates_5fdirect_5fexchange_5frate_5fv2_2frequest_2eproto,
  &::descriptor_table_sdk_2fstream_2faggregates_5fdirect_5fexchange_5frate_5fv2_2fresponse_2eproto,
  &::descriptor_table_sdk_2fstream_2faggregates_5fohlcv_5fv1_2frequest_2eproto,
  &::descriptor_table_sdk_2fstream_2faggregates_5fohlcv_5fv1_2fresponse_2eproto,
  &::descriptor_table_sdk_2fstream_2faggregates_5fspot_5fexchange_5frate_5fv2_2frequest_2eproto,
  &::descriptor_table_sdk_2fstream_2faggregates_5fspot_5fexchange_5frate_5fv2_2fresponse_2eproto,
  &::descriptor_table_sdk_2fstream_2faggregates_5fvwap_5fv1_2frequest_2eproto,
  &::descriptor_table_sdk_2fstream_2faggregates_5fvwap_5fv1_2fresponse_2eproto,
  &::descriptor_table_sdk_2fstream_2fcomposite_5findices_5fv1_2frequest_2eproto,
  &::descriptor_table_sdk_2fstream_2fcomposite_5findices_5fv1_2fresponse_2eproto,
  &::descriptor_table_sdk_2fstream_2fconstant_5fduration_5findices_5fv1_2frequest_2eproto,
  &::descriptor_table_sdk_2fstream_2fconstant_5fduration_5findices_5fv1_2fresponse_2eproto,
  &::descriptor_table_sdk_2fstream_2fderivatives_5finstrument_5fmetrics_5fv1_2frequest_2eproto,
  &::descriptor_table_sdk_2fstream_2fderivatives_5finstrument_5fmetrics_5fv1_2fresponse_2eproto,
  &::descriptor_table_sdk_2fstream_2fexotic_5findices_5fv1_2frequest_2eproto,
  &::descriptor_table_sdk_2fstream_2fexotic_5findices_5fv1_2fresponse_2eproto,
  &::descriptor_table_sdk_2fstream_2findex_5fforex_5frate_5fv1_2frequest_2eproto,
  &::descriptor_table_sdk_2fstream_2findex_5fforex_5frate_5fv1_2fresponse_2eproto,
  &::descriptor_table_sdk_2fstream_2findex_5fmulti_5fassets_5fv1_2frequest_2eproto,
  &::descriptor_table_sdk_2fstream_2findex_5fmulti_5fassets_5fv1_2fresponse_2eproto,
  &::descriptor_table_sdk_2fstream_2findex_5fv1_2frequest_2eproto,
  &::descriptor_table_sdk_2fstream_2findex_5fv1_2fresponse_2eproto,
  &::descriptor_table_sdk_2fstream_2fiv_5fsvi_5fparameters_5fv1_2frequest_2eproto,
  &::descriptor_table_sdk_2fstream_2fiv_5fsvi_5fparameters_5fv1_2fresponse_2eproto,
  &::descriptor_table_sdk_2fstream_2fmarket_5fupdate_5fv1_2frequest_2eproto,
  &::descriptor_table_sdk_2fstream_2fmarket_5fupdate_5fv1_2fresponse_2eproto,
  &::descriptor_table_sdk_2fstream_2forderbookl2_5fv1_2frequest_2eproto,
  &::descriptor_table_sdk_2fstream_2forderbookl2_5fv1_2fresponse_2eproto,
  &::descriptor_table_sdk_2fstream_2ftrades_5fv1_2frequest_2eproto,
  &::descriptor_table_sdk_2fstream_2ftrades_5fv1_2fresponse_2eproto,
};
static ::_pbi::once_flag descriptor_table_sdk_2fsdk_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_sdk_2fsdk_2eproto = {
    false, false, 4619, descriptor_table_protodef_sdk_2fsdk_2eproto,
    "sdk/sdk.proto",
    &descriptor_table_sdk_2fsdk_2eproto_once, descriptor_table_sdk_2fsdk_2eproto_deps, 36, 0,
    schemas, file_default_instances, TableStruct_sdk_2fsdk_2eproto::offsets,
    nullptr, file_level_enum_descriptors_sdk_2fsdk_2eproto,
    file_level_service_descriptors_sdk_2fsdk_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_sdk_2fsdk_2eproto_getter() {
  return &descriptor_table_sdk_2fsdk_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_sdk_2fsdk_2eproto(&descriptor_table_sdk_2fsdk_2eproto);
namespace kaikosdk {

// @@protoc_insertion_point(namespace_scope)
}  // namespace kaikosdk
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
