// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk/sdk.proto

#include "sdk/sdk.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace kaikosdk {
}  // namespace kaikosdk
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_sdk_2fsdk_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_sdk_2fsdk_2eproto = nullptr;
const uint32_t TableStruct_sdk_2fsdk_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_sdk_2fsdk_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\rsdk/sdk.proto\022\010kaikosdk\032,sdk/stream/ag"
  "gregated_price_v1/request.proto\032-sdk/str"
  "eam/aggregated_price_v1/response.proto\032,"
  "sdk/stream/aggregates_ohlcv_v1/request.p"
  "roto\032-sdk/stream/aggregates_ohlcv_v1/res"
  "ponse.proto\032+sdk/stream/aggregates_vwap_"
  "v1/request.proto\032,sdk/stream/aggregates_"
  "vwap_v1/response.proto\032;sdk/stream/aggre"
  "gates_direct_exchange_rate_v1/request.pr"
  "oto\032<sdk/stream/aggregates_direct_exchan"
  "ge_rate_v1/response.proto\0329sdk/stream/ag"
  "gregates_spot_exchange_rate_v1/request.p"
  "roto\032:sdk/stream/aggregates_spot_exchang"
  "e_rate_v1/response.proto\032-sdk/stream/der"
  "ivatives_price_v2/request.proto\032.sdk/str"
  "eam/derivatives_price_v2/response.proto\032"
  "!sdk/stream/index_v1/request.proto\032\"sdk/"
  "stream/index_v1/response.proto\032)sdk/stre"
  "am/market_update_v1/request.proto\032*sdk/s"
  "tream/market_update_v1/response.proto\032\"s"
  "dk/stream/trades_v1/request.proto\032#sdk/s"
  "tream/trades_v1/response.proto2\206\001\n\036Strea"
  "mAggregatedPriceServiceV1\022d\n\tSubscribe\022("
  ".kaikosdk.StreamAggregatedPriceRequestV1"
  "\032).kaikosdk.StreamAggregatedPriceRespons"
  "eV1\"\0000\0012\206\001\n\036StreamAggregatesOHLCVService"
  "V1\022d\n\tSubscribe\022(.kaikosdk.StreamAggrega"
  "tesOHLCVRequestV1\032).kaikosdk.StreamAggre"
  "gatesOHLCVResponseV1\"\0000\0012\247\001\n)StreamAggre"
  "gatesSpotExchangeRateServiceV1\022z\n\tSubscr"
  "ibe\0223.kaikosdk.StreamAggregatesSpotExcha"
  "ngeRateRequestV1\0324.kaikosdk.StreamAggreg"
  "atesSpotExchangeRateResponseV1\"\0000\0012\255\001\n+S"
  "treamAggregatesDirectExchangeRateService"
  "V1\022~\n\tSubscribe\0225.kaikosdk.StreamAggrega"
  "tesDirectExchangeRateRequestV1\0326.kaikosd"
  "k.StreamAggregatesDirectExchangeRateResp"
  "onseV1\"\0000\0012k\n\025StreamTradesServiceV1\022R\n\tS"
  "ubscribe\022\037.kaikosdk.StreamTradesRequestV"
  "1\032 .kaikosdk.StreamTradesResponseV1\"\0000\0012"
  "\203\001\n\035StreamAggregatesVWAPServiceV1\022b\n\tSub"
  "scribe\022\'.kaikosdk.StreamAggregatesVWAPRe"
  "questV1\032(.kaikosdk.StreamAggregatesVWAPR"
  "esponseV1\"\0000\0012\211\001\n\037StreamDerivativesPrice"
  "ServiceV2\022f\n\tSubscribe\022).kaikosdk.Stream"
  "DerivativesPriceRequestV2\032*.kaikosdk.Str"
  "eamDerivativesPriceResponseV2\"\0000\0012v\n\024Str"
  "eamIndexServiceV1\022^\n\tSubscribe\022%.kaikosd"
  "k.StreamIndexServiceRequestV1\032&.kaikosdk"
  ".StreamIndexServiceResponseV1\"\0000\0012}\n\033Str"
  "eamMarketUpdateServiceV1\022^\n\tSubscribe\022%."
  "kaikosdk.StreamMarketUpdateRequestV1\032&.k"
  "aikosdk.StreamMarketUpdateResponseV1\"\0000\001"
  "BW\n\rcom.kaiko.sdkB\010SdkProtoP\001Z/github.co"
  "m/challengerdeep/kaiko-go-sdk;kaikosdk\252\002"
  "\010KaikoSdkb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_sdk_2fsdk_2eproto_deps[18] = {
  &::descriptor_table_sdk_2fstream_2faggregated_5fprice_5fv1_2frequest_2eproto,
  &::descriptor_table_sdk_2fstream_2faggregated_5fprice_5fv1_2fresponse_2eproto,
  &::descriptor_table_sdk_2fstream_2faggregates_5fdirect_5fexchange_5frate_5fv1_2frequest_2eproto,
  &::descriptor_table_sdk_2fstream_2faggregates_5fdirect_5fexchange_5frate_5fv1_2fresponse_2eproto,
  &::descriptor_table_sdk_2fstream_2faggregates_5fohlcv_5fv1_2frequest_2eproto,
  &::descriptor_table_sdk_2fstream_2faggregates_5fohlcv_5fv1_2fresponse_2eproto,
  &::descriptor_table_sdk_2fstream_2faggregates_5fspot_5fexchange_5frate_5fv1_2frequest_2eproto,
  &::descriptor_table_sdk_2fstream_2faggregates_5fspot_5fexchange_5frate_5fv1_2fresponse_2eproto,
  &::descriptor_table_sdk_2fstream_2faggregates_5fvwap_5fv1_2frequest_2eproto,
  &::descriptor_table_sdk_2fstream_2faggregates_5fvwap_5fv1_2fresponse_2eproto,
  &::descriptor_table_sdk_2fstream_2fderivatives_5fprice_5fv2_2frequest_2eproto,
  &::descriptor_table_sdk_2fstream_2fderivatives_5fprice_5fv2_2fresponse_2eproto,
  &::descriptor_table_sdk_2fstream_2findex_5fv1_2frequest_2eproto,
  &::descriptor_table_sdk_2fstream_2findex_5fv1_2fresponse_2eproto,
  &::descriptor_table_sdk_2fstream_2fmarket_5fupdate_5fv1_2frequest_2eproto,
  &::descriptor_table_sdk_2fstream_2fmarket_5fupdate_5fv1_2fresponse_2eproto,
  &::descriptor_table_sdk_2fstream_2ftrades_5fv1_2frequest_2eproto,
  &::descriptor_table_sdk_2fstream_2ftrades_5fv1_2fresponse_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_sdk_2fsdk_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_sdk_2fsdk_2eproto = {
  false, false, 2217, descriptor_table_protodef_sdk_2fsdk_2eproto, "sdk/sdk.proto", 
  &descriptor_table_sdk_2fsdk_2eproto_once, descriptor_table_sdk_2fsdk_2eproto_deps, 18, 0,
  schemas, file_default_instances, TableStruct_sdk_2fsdk_2eproto::offsets,
  nullptr, file_level_enum_descriptors_sdk_2fsdk_2eproto, file_level_service_descriptors_sdk_2fsdk_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_sdk_2fsdk_2eproto_getter() {
  return &descriptor_table_sdk_2fsdk_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_sdk_2fsdk_2eproto(&descriptor_table_sdk_2fsdk_2eproto);
namespace kaikosdk {

// @@protoc_insertion_point(namespace_scope)
}  // namespace kaikosdk
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
