// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk/stream/canton_oracle_v2/response.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_sdk_2fstream_2fcanton_5foracle_5fv2_2fresponse_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_sdk_2fstream_2fcanton_5foracle_5fv2_2fresponse_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_sdk_2fstream_2fcanton_5foracle_5fv2_2fresponse_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_sdk_2fstream_2fcanton_5foracle_5fv2_2fresponse_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_sdk_2fstream_2fcanton_5foracle_5fv2_2fresponse_2eproto;
namespace kaikosdk {
class CostV2;
struct CostV2DefaultTypeInternal;
extern CostV2DefaultTypeInternal _CostV2_default_instance_;
class InstrumentIdV2;
struct InstrumentIdV2DefaultTypeInternal;
extern InstrumentIdV2DefaultTypeInternal _InstrumentIdV2_default_instance_;
class QuoteV2;
struct QuoteV2DefaultTypeInternal;
extern QuoteV2DefaultTypeInternal _QuoteV2_default_instance_;
class SignedPayloadV2;
struct SignedPayloadV2DefaultTypeInternal;
extern SignedPayloadV2DefaultTypeInternal _SignedPayloadV2_default_instance_;
class StreamCantonOracleServiceResponseV2;
struct StreamCantonOracleServiceResponseV2DefaultTypeInternal;
extern StreamCantonOracleServiceResponseV2DefaultTypeInternal _StreamCantonOracleServiceResponseV2_default_instance_;
class VerifierContract;
struct VerifierContractDefaultTypeInternal;
extern VerifierContractDefaultTypeInternal _VerifierContract_default_instance_;
}  // namespace kaikosdk
PROTOBUF_NAMESPACE_OPEN
template<> ::kaikosdk::CostV2* Arena::CreateMaybeMessage<::kaikosdk::CostV2>(Arena*);
template<> ::kaikosdk::InstrumentIdV2* Arena::CreateMaybeMessage<::kaikosdk::InstrumentIdV2>(Arena*);
template<> ::kaikosdk::QuoteV2* Arena::CreateMaybeMessage<::kaikosdk::QuoteV2>(Arena*);
template<> ::kaikosdk::SignedPayloadV2* Arena::CreateMaybeMessage<::kaikosdk::SignedPayloadV2>(Arena*);
template<> ::kaikosdk::StreamCantonOracleServiceResponseV2* Arena::CreateMaybeMessage<::kaikosdk::StreamCantonOracleServiceResponseV2>(Arena*);
template<> ::kaikosdk::VerifierContract* Arena::CreateMaybeMessage<::kaikosdk::VerifierContract>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace kaikosdk {

// ===================================================================

class StreamCantonOracleServiceResponseV2 final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:kaikosdk.StreamCantonOracleServiceResponseV2) */ {
 public:
  inline StreamCantonOracleServiceResponseV2() : StreamCantonOracleServiceResponseV2(nullptr) {}
  ~StreamCantonOracleServiceResponseV2() override;
  explicit PROTOBUF_CONSTEXPR StreamCantonOracleServiceResponseV2(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  StreamCantonOracleServiceResponseV2(const StreamCantonOracleServiceResponseV2& from);
  StreamCantonOracleServiceResponseV2(StreamCantonOracleServiceResponseV2&& from) noexcept
    : StreamCantonOracleServiceResponseV2() {
    *this = ::std::move(from);
  }

  inline StreamCantonOracleServiceResponseV2& operator=(const StreamCantonOracleServiceResponseV2& from) {
    CopyFrom(from);
    return *this;
  }
  inline StreamCantonOracleServiceResponseV2& operator=(StreamCantonOracleServiceResponseV2&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StreamCantonOracleServiceResponseV2& default_instance() {
    return *internal_default_instance();
  }
  static inline const StreamCantonOracleServiceResponseV2* internal_default_instance() {
    return reinterpret_cast<const StreamCantonOracleServiceResponseV2*>(
               &_StreamCantonOracleServiceResponseV2_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(StreamCantonOracleServiceResponseV2& a, StreamCantonOracleServiceResponseV2& b) {
    a.Swap(&b);
  }
  inline void Swap(StreamCantonOracleServiceResponseV2* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StreamCantonOracleServiceResponseV2* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StreamCantonOracleServiceResponseV2* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<StreamCantonOracleServiceResponseV2>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const StreamCantonOracleServiceResponseV2& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const StreamCantonOracleServiceResponseV2& from) {
    StreamCantonOracleServiceResponseV2::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StreamCantonOracleServiceResponseV2* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "kaikosdk.StreamCantonOracleServiceResponseV2";
  }
  protected:
  explicit StreamCantonOracleServiceResponseV2(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNetworkFieldNumber = 1,
    kFeedCategoryFieldNumber = 2,
    kFeedIdFieldNumber = 3,
    kSignatureFieldNumber = 5,
    kCanonicalHashFieldNumber = 6,
    kPayloadFieldNumber = 4,
    kVerifierContractFieldNumber = 7,
  };
  // string network = 1;
  void clear_network();
  const std::string& network() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_network(ArgT0&& arg0, ArgT... args);
  std::string* mutable_network();
  PROTOBUF_NODISCARD std::string* release_network();
  void set_allocated_network(std::string* network);
  private:
  const std::string& _internal_network() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_network(const std::string& value);
  std::string* _internal_mutable_network();
  public:

  // string feed_category = 2;
  void clear_feed_category();
  const std::string& feed_category() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_feed_category(ArgT0&& arg0, ArgT... args);
  std::string* mutable_feed_category();
  PROTOBUF_NODISCARD std::string* release_feed_category();
  void set_allocated_feed_category(std::string* feed_category);
  private:
  const std::string& _internal_feed_category() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_feed_category(const std::string& value);
  std::string* _internal_mutable_feed_category();
  public:

  // string feed_id = 3;
  void clear_feed_id();
  const std::string& feed_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_feed_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_feed_id();
  PROTOBUF_NODISCARD std::string* release_feed_id();
  void set_allocated_feed_id(std::string* feed_id);
  private:
  const std::string& _internal_feed_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_feed_id(const std::string& value);
  std::string* _internal_mutable_feed_id();
  public:

  // string signature = 5;
  void clear_signature();
  const std::string& signature() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_signature(ArgT0&& arg0, ArgT... args);
  std::string* mutable_signature();
  PROTOBUF_NODISCARD std::string* release_signature();
  void set_allocated_signature(std::string* signature);
  private:
  const std::string& _internal_signature() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_signature(const std::string& value);
  std::string* _internal_mutable_signature();
  public:

  // string canonical_hash = 6;
  void clear_canonical_hash();
  const std::string& canonical_hash() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_canonical_hash(ArgT0&& arg0, ArgT... args);
  std::string* mutable_canonical_hash();
  PROTOBUF_NODISCARD std::string* release_canonical_hash();
  void set_allocated_canonical_hash(std::string* canonical_hash);
  private:
  const std::string& _internal_canonical_hash() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_canonical_hash(const std::string& value);
  std::string* _internal_mutable_canonical_hash();
  public:

  // .kaikosdk.SignedPayloadV2 payload = 4;
  bool has_payload() const;
  private:
  bool _internal_has_payload() const;
  public:
  void clear_payload();
  const ::kaikosdk::SignedPayloadV2& payload() const;
  PROTOBUF_NODISCARD ::kaikosdk::SignedPayloadV2* release_payload();
  ::kaikosdk::SignedPayloadV2* mutable_payload();
  void set_allocated_payload(::kaikosdk::SignedPayloadV2* payload);
  private:
  const ::kaikosdk::SignedPayloadV2& _internal_payload() const;
  ::kaikosdk::SignedPayloadV2* _internal_mutable_payload();
  public:
  void unsafe_arena_set_allocated_payload(
      ::kaikosdk::SignedPayloadV2* payload);
  ::kaikosdk::SignedPayloadV2* unsafe_arena_release_payload();

  // .kaikosdk.VerifierContract verifier_contract = 7;
  bool has_verifier_contract() const;
  private:
  bool _internal_has_verifier_contract() const;
  public:
  void clear_verifier_contract();
  const ::kaikosdk::VerifierContract& verifier_contract() const;
  PROTOBUF_NODISCARD ::kaikosdk::VerifierContract* release_verifier_contract();
  ::kaikosdk::VerifierContract* mutable_verifier_contract();
  void set_allocated_verifier_contract(::kaikosdk::VerifierContract* verifier_contract);
  private:
  const ::kaikosdk::VerifierContract& _internal_verifier_contract() const;
  ::kaikosdk::VerifierContract* _internal_mutable_verifier_contract();
  public:
  void unsafe_arena_set_allocated_verifier_contract(
      ::kaikosdk::VerifierContract* verifier_contract);
  ::kaikosdk::VerifierContract* unsafe_arena_release_verifier_contract();

  // @@protoc_insertion_point(class_scope:kaikosdk.StreamCantonOracleServiceResponseV2)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr network_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr feed_category_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr feed_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr signature_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr canonical_hash_;
    ::kaikosdk::SignedPayloadV2* payload_;
    ::kaikosdk::VerifierContract* verifier_contract_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_sdk_2fstream_2fcanton_5foracle_5fv2_2fresponse_2eproto;
};
// -------------------------------------------------------------------

class VerifierContract final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:kaikosdk.VerifierContract) */ {
 public:
  inline VerifierContract() : VerifierContract(nullptr) {}
  ~VerifierContract() override;
  explicit PROTOBUF_CONSTEXPR VerifierContract(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  VerifierContract(const VerifierContract& from);
  VerifierContract(VerifierContract&& from) noexcept
    : VerifierContract() {
    *this = ::std::move(from);
  }

  inline VerifierContract& operator=(const VerifierContract& from) {
    CopyFrom(from);
    return *this;
  }
  inline VerifierContract& operator=(VerifierContract&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const VerifierContract& default_instance() {
    return *internal_default_instance();
  }
  static inline const VerifierContract* internal_default_instance() {
    return reinterpret_cast<const VerifierContract*>(
               &_VerifierContract_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(VerifierContract& a, VerifierContract& b) {
    a.Swap(&b);
  }
  inline void Swap(VerifierContract* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VerifierContract* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VerifierContract* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<VerifierContract>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const VerifierContract& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const VerifierContract& from) {
    VerifierContract::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(VerifierContract* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "kaikosdk.VerifierContract";
  }
  protected:
  explicit VerifierContract(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTemplateIdFieldNumber = 1,
    kContractIdFieldNumber = 2,
    kCreatedEventBlobFieldNumber = 3,
  };
  // string templateId = 1;
  void clear_templateid();
  const std::string& templateid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_templateid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_templateid();
  PROTOBUF_NODISCARD std::string* release_templateid();
  void set_allocated_templateid(std::string* templateid);
  private:
  const std::string& _internal_templateid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_templateid(const std::string& value);
  std::string* _internal_mutable_templateid();
  public:

  // string contractId = 2;
  void clear_contractid();
  const std::string& contractid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_contractid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_contractid();
  PROTOBUF_NODISCARD std::string* release_contractid();
  void set_allocated_contractid(std::string* contractid);
  private:
  const std::string& _internal_contractid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_contractid(const std::string& value);
  std::string* _internal_mutable_contractid();
  public:

  // string createdEventBlob = 3;
  void clear_createdeventblob();
  const std::string& createdeventblob() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_createdeventblob(ArgT0&& arg0, ArgT... args);
  std::string* mutable_createdeventblob();
  PROTOBUF_NODISCARD std::string* release_createdeventblob();
  void set_allocated_createdeventblob(std::string* createdeventblob);
  private:
  const std::string& _internal_createdeventblob() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_createdeventblob(const std::string& value);
  std::string* _internal_mutable_createdeventblob();
  public:

  // @@protoc_insertion_point(class_scope:kaikosdk.VerifierContract)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr templateid_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr contractid_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr createdeventblob_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_sdk_2fstream_2fcanton_5foracle_5fv2_2fresponse_2eproto;
};
// -------------------------------------------------------------------

class SignedPayloadV2 final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:kaikosdk.SignedPayloadV2) */ {
 public:
  inline SignedPayloadV2() : SignedPayloadV2(nullptr) {}
  ~SignedPayloadV2() override;
  explicit PROTOBUF_CONSTEXPR SignedPayloadV2(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SignedPayloadV2(const SignedPayloadV2& from);
  SignedPayloadV2(SignedPayloadV2&& from) noexcept
    : SignedPayloadV2() {
    *this = ::std::move(from);
  }

  inline SignedPayloadV2& operator=(const SignedPayloadV2& from) {
    CopyFrom(from);
    return *this;
  }
  inline SignedPayloadV2& operator=(SignedPayloadV2&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SignedPayloadV2& default_instance() {
    return *internal_default_instance();
  }
  static inline const SignedPayloadV2* internal_default_instance() {
    return reinterpret_cast<const SignedPayloadV2*>(
               &_SignedPayloadV2_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(SignedPayloadV2& a, SignedPayloadV2& b) {
    a.Swap(&b);
  }
  inline void Swap(SignedPayloadV2* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SignedPayloadV2* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SignedPayloadV2* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SignedPayloadV2>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SignedPayloadV2& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SignedPayloadV2& from) {
    SignedPayloadV2::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SignedPayloadV2* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "kaikosdk.SignedPayloadV2";
  }
  protected:
  explicit SignedPayloadV2(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPublishedAtFieldNumber = 1,
    kExpiresAtFieldNumber = 2,
    kPayeeFieldNumber = 5,
    kCostFieldNumber = 3,
    kQuoteFieldNumber = 4,
  };
  // string publishedAt = 1;
  void clear_publishedat();
  const std::string& publishedat() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_publishedat(ArgT0&& arg0, ArgT... args);
  std::string* mutable_publishedat();
  PROTOBUF_NODISCARD std::string* release_publishedat();
  void set_allocated_publishedat(std::string* publishedat);
  private:
  const std::string& _internal_publishedat() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_publishedat(const std::string& value);
  std::string* _internal_mutable_publishedat();
  public:

  // string expiresAt = 2;
  void clear_expiresat();
  const std::string& expiresat() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_expiresat(ArgT0&& arg0, ArgT... args);
  std::string* mutable_expiresat();
  PROTOBUF_NODISCARD std::string* release_expiresat();
  void set_allocated_expiresat(std::string* expiresat);
  private:
  const std::string& _internal_expiresat() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_expiresat(const std::string& value);
  std::string* _internal_mutable_expiresat();
  public:

  // string payee = 5;
  void clear_payee();
  const std::string& payee() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_payee(ArgT0&& arg0, ArgT... args);
  std::string* mutable_payee();
  PROTOBUF_NODISCARD std::string* release_payee();
  void set_allocated_payee(std::string* payee);
  private:
  const std::string& _internal_payee() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_payee(const std::string& value);
  std::string* _internal_mutable_payee();
  public:

  // optional .kaikosdk.CostV2 cost = 3;
  bool has_cost() const;
  private:
  bool _internal_has_cost() const;
  public:
  void clear_cost();
  const ::kaikosdk::CostV2& cost() const;
  PROTOBUF_NODISCARD ::kaikosdk::CostV2* release_cost();
  ::kaikosdk::CostV2* mutable_cost();
  void set_allocated_cost(::kaikosdk::CostV2* cost);
  private:
  const ::kaikosdk::CostV2& _internal_cost() const;
  ::kaikosdk::CostV2* _internal_mutable_cost();
  public:
  void unsafe_arena_set_allocated_cost(
      ::kaikosdk::CostV2* cost);
  ::kaikosdk::CostV2* unsafe_arena_release_cost();

  // .kaikosdk.QuoteV2 quote = 4;
  bool has_quote() const;
  private:
  bool _internal_has_quote() const;
  public:
  void clear_quote();
  const ::kaikosdk::QuoteV2& quote() const;
  PROTOBUF_NODISCARD ::kaikosdk::QuoteV2* release_quote();
  ::kaikosdk::QuoteV2* mutable_quote();
  void set_allocated_quote(::kaikosdk::QuoteV2* quote);
  private:
  const ::kaikosdk::QuoteV2& _internal_quote() const;
  ::kaikosdk::QuoteV2* _internal_mutable_quote();
  public:
  void unsafe_arena_set_allocated_quote(
      ::kaikosdk::QuoteV2* quote);
  ::kaikosdk::QuoteV2* unsafe_arena_release_quote();

  // @@protoc_insertion_point(class_scope:kaikosdk.SignedPayloadV2)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr publishedat_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr expiresat_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr payee_;
    ::kaikosdk::CostV2* cost_;
    ::kaikosdk::QuoteV2* quote_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_sdk_2fstream_2fcanton_5foracle_5fv2_2fresponse_2eproto;
};
// -------------------------------------------------------------------

class CostV2 final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:kaikosdk.CostV2) */ {
 public:
  inline CostV2() : CostV2(nullptr) {}
  ~CostV2() override;
  explicit PROTOBUF_CONSTEXPR CostV2(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CostV2(const CostV2& from);
  CostV2(CostV2&& from) noexcept
    : CostV2() {
    *this = ::std::move(from);
  }

  inline CostV2& operator=(const CostV2& from) {
    CopyFrom(from);
    return *this;
  }
  inline CostV2& operator=(CostV2&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CostV2& default_instance() {
    return *internal_default_instance();
  }
  static inline const CostV2* internal_default_instance() {
    return reinterpret_cast<const CostV2*>(
               &_CostV2_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(CostV2& a, CostV2& b) {
    a.Swap(&b);
  }
  inline void Swap(CostV2* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CostV2* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CostV2* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CostV2>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CostV2& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CostV2& from) {
    CostV2::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CostV2* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "kaikosdk.CostV2";
  }
  protected:
  explicit CostV2(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFeeFieldNumber = 1,
    kInstrumentFieldNumber = 2,
  };
  // string fee = 1;
  void clear_fee();
  const std::string& fee() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_fee(ArgT0&& arg0, ArgT... args);
  std::string* mutable_fee();
  PROTOBUF_NODISCARD std::string* release_fee();
  void set_allocated_fee(std::string* fee);
  private:
  const std::string& _internal_fee() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_fee(const std::string& value);
  std::string* _internal_mutable_fee();
  public:

  // .kaikosdk.InstrumentIdV2 instrument = 2;
  bool has_instrument() const;
  private:
  bool _internal_has_instrument() const;
  public:
  void clear_instrument();
  const ::kaikosdk::InstrumentIdV2& instrument() const;
  PROTOBUF_NODISCARD ::kaikosdk::InstrumentIdV2* release_instrument();
  ::kaikosdk::InstrumentIdV2* mutable_instrument();
  void set_allocated_instrument(::kaikosdk::InstrumentIdV2* instrument);
  private:
  const ::kaikosdk::InstrumentIdV2& _internal_instrument() const;
  ::kaikosdk::InstrumentIdV2* _internal_mutable_instrument();
  public:
  void unsafe_arena_set_allocated_instrument(
      ::kaikosdk::InstrumentIdV2* instrument);
  ::kaikosdk::InstrumentIdV2* unsafe_arena_release_instrument();

  // @@protoc_insertion_point(class_scope:kaikosdk.CostV2)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr fee_;
    ::kaikosdk::InstrumentIdV2* instrument_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_sdk_2fstream_2fcanton_5foracle_5fv2_2fresponse_2eproto;
};
// -------------------------------------------------------------------

class InstrumentIdV2 final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:kaikosdk.InstrumentIdV2) */ {
 public:
  inline InstrumentIdV2() : InstrumentIdV2(nullptr) {}
  ~InstrumentIdV2() override;
  explicit PROTOBUF_CONSTEXPR InstrumentIdV2(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  InstrumentIdV2(const InstrumentIdV2& from);
  InstrumentIdV2(InstrumentIdV2&& from) noexcept
    : InstrumentIdV2() {
    *this = ::std::move(from);
  }

  inline InstrumentIdV2& operator=(const InstrumentIdV2& from) {
    CopyFrom(from);
    return *this;
  }
  inline InstrumentIdV2& operator=(InstrumentIdV2&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const InstrumentIdV2& default_instance() {
    return *internal_default_instance();
  }
  static inline const InstrumentIdV2* internal_default_instance() {
    return reinterpret_cast<const InstrumentIdV2*>(
               &_InstrumentIdV2_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(InstrumentIdV2& a, InstrumentIdV2& b) {
    a.Swap(&b);
  }
  inline void Swap(InstrumentIdV2* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InstrumentIdV2* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  InstrumentIdV2* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<InstrumentIdV2>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const InstrumentIdV2& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const InstrumentIdV2& from) {
    InstrumentIdV2::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InstrumentIdV2* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "kaikosdk.InstrumentIdV2";
  }
  protected:
  explicit InstrumentIdV2(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAdminFieldNumber = 1,
    kIdFieldNumber = 2,
  };
  // string admin = 1;
  void clear_admin();
  const std::string& admin() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_admin(ArgT0&& arg0, ArgT... args);
  std::string* mutable_admin();
  PROTOBUF_NODISCARD std::string* release_admin();
  void set_allocated_admin(std::string* admin);
  private:
  const std::string& _internal_admin() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_admin(const std::string& value);
  std::string* _internal_mutable_admin();
  public:

  // string id = 2;
  void clear_id();
  const std::string& id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_id();
  PROTOBUF_NODISCARD std::string* release_id();
  void set_allocated_id(std::string* id);
  private:
  const std::string& _internal_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_id(const std::string& value);
  std::string* _internal_mutable_id();
  public:

  // @@protoc_insertion_point(class_scope:kaikosdk.InstrumentIdV2)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr admin_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_sdk_2fstream_2fcanton_5foracle_5fv2_2fresponse_2eproto;
};
// -------------------------------------------------------------------

class QuoteV2 final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:kaikosdk.QuoteV2) */ {
 public:
  inline QuoteV2() : QuoteV2(nullptr) {}
  ~QuoteV2() override;
  explicit PROTOBUF_CONSTEXPR QuoteV2(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  QuoteV2(const QuoteV2& from);
  QuoteV2(QuoteV2&& from) noexcept
    : QuoteV2() {
    *this = ::std::move(from);
  }

  inline QuoteV2& operator=(const QuoteV2& from) {
    CopyFrom(from);
    return *this;
  }
  inline QuoteV2& operator=(QuoteV2&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const QuoteV2& default_instance() {
    return *internal_default_instance();
  }
  static inline const QuoteV2* internal_default_instance() {
    return reinterpret_cast<const QuoteV2*>(
               &_QuoteV2_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(QuoteV2& a, QuoteV2& b) {
    a.Swap(&b);
  }
  inline void Swap(QuoteV2* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(QuoteV2* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  QuoteV2* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<QuoteV2>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const QuoteV2& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const QuoteV2& from) {
    QuoteV2::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(QuoteV2* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "kaikosdk.QuoteV2";
  }
  protected:
  explicit QuoteV2(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFeedIdFieldNumber = 1,
    kPriceFieldNumber = 2,
    kPriceTimeFieldNumber = 3,
  };
  // string feedId = 1;
  void clear_feedid();
  const std::string& feedid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_feedid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_feedid();
  PROTOBUF_NODISCARD std::string* release_feedid();
  void set_allocated_feedid(std::string* feedid);
  private:
  const std::string& _internal_feedid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_feedid(const std::string& value);
  std::string* _internal_mutable_feedid();
  public:

  // string price = 2;
  void clear_price();
  const std::string& price() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_price(ArgT0&& arg0, ArgT... args);
  std::string* mutable_price();
  PROTOBUF_NODISCARD std::string* release_price();
  void set_allocated_price(std::string* price);
  private:
  const std::string& _internal_price() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_price(const std::string& value);
  std::string* _internal_mutable_price();
  public:

  // string priceTime = 3;
  void clear_pricetime();
  const std::string& pricetime() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_pricetime(ArgT0&& arg0, ArgT... args);
  std::string* mutable_pricetime();
  PROTOBUF_NODISCARD std::string* release_pricetime();
  void set_allocated_pricetime(std::string* pricetime);
  private:
  const std::string& _internal_pricetime() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_pricetime(const std::string& value);
  std::string* _internal_mutable_pricetime();
  public:

  // @@protoc_insertion_point(class_scope:kaikosdk.QuoteV2)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr feedid_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr price_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr pricetime_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_sdk_2fstream_2fcanton_5foracle_5fv2_2fresponse_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// StreamCantonOracleServiceResponseV2

// string network = 1;
inline void StreamCantonOracleServiceResponseV2::clear_network() {
  _impl_.network_.ClearToEmpty();
}
inline const std::string& StreamCantonOracleServiceResponseV2::network() const {
  // @@protoc_insertion_point(field_get:kaikosdk.StreamCantonOracleServiceResponseV2.network)
  return _internal_network();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void StreamCantonOracleServiceResponseV2::set_network(ArgT0&& arg0, ArgT... args) {
 
 _impl_.network_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:kaikosdk.StreamCantonOracleServiceResponseV2.network)
}
inline std::string* StreamCantonOracleServiceResponseV2::mutable_network() {
  std::string* _s = _internal_mutable_network();
  // @@protoc_insertion_point(field_mutable:kaikosdk.StreamCantonOracleServiceResponseV2.network)
  return _s;
}
inline const std::string& StreamCantonOracleServiceResponseV2::_internal_network() const {
  return _impl_.network_.Get();
}
inline void StreamCantonOracleServiceResponseV2::_internal_set_network(const std::string& value) {
  
  _impl_.network_.Set(value, GetArenaForAllocation());
}
inline std::string* StreamCantonOracleServiceResponseV2::_internal_mutable_network() {
  
  return _impl_.network_.Mutable(GetArenaForAllocation());
}
inline std::string* StreamCantonOracleServiceResponseV2::release_network() {
  // @@protoc_insertion_point(field_release:kaikosdk.StreamCantonOracleServiceResponseV2.network)
  return _impl_.network_.Release();
}
inline void StreamCantonOracleServiceResponseV2::set_allocated_network(std::string* network) {
  if (network != nullptr) {
    
  } else {
    
  }
  _impl_.network_.SetAllocated(network, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.network_.IsDefault()) {
    _impl_.network_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:kaikosdk.StreamCantonOracleServiceResponseV2.network)
}

// string feed_category = 2;
inline void StreamCantonOracleServiceResponseV2::clear_feed_category() {
  _impl_.feed_category_.ClearToEmpty();
}
inline const std::string& StreamCantonOracleServiceResponseV2::feed_category() const {
  // @@protoc_insertion_point(field_get:kaikosdk.StreamCantonOracleServiceResponseV2.feed_category)
  return _internal_feed_category();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void StreamCantonOracleServiceResponseV2::set_feed_category(ArgT0&& arg0, ArgT... args) {
 
 _impl_.feed_category_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:kaikosdk.StreamCantonOracleServiceResponseV2.feed_category)
}
inline std::string* StreamCantonOracleServiceResponseV2::mutable_feed_category() {
  std::string* _s = _internal_mutable_feed_category();
  // @@protoc_insertion_point(field_mutable:kaikosdk.StreamCantonOracleServiceResponseV2.feed_category)
  return _s;
}
inline const std::string& StreamCantonOracleServiceResponseV2::_internal_feed_category() const {
  return _impl_.feed_category_.Get();
}
inline void StreamCantonOracleServiceResponseV2::_internal_set_feed_category(const std::string& value) {
  
  _impl_.feed_category_.Set(value, GetArenaForAllocation());
}
inline std::string* StreamCantonOracleServiceResponseV2::_internal_mutable_feed_category() {
  
  return _impl_.feed_category_.Mutable(GetArenaForAllocation());
}
inline std::string* StreamCantonOracleServiceResponseV2::release_feed_category() {
  // @@protoc_insertion_point(field_release:kaikosdk.StreamCantonOracleServiceResponseV2.feed_category)
  return _impl_.feed_category_.Release();
}
inline void StreamCantonOracleServiceResponseV2::set_allocated_feed_category(std::string* feed_category) {
  if (feed_category != nullptr) {
    
  } else {
    
  }
  _impl_.feed_category_.SetAllocated(feed_category, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.feed_category_.IsDefault()) {
    _impl_.feed_category_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:kaikosdk.StreamCantonOracleServiceResponseV2.feed_category)
}

// string feed_id = 3;
inline void StreamCantonOracleServiceResponseV2::clear_feed_id() {
  _impl_.feed_id_.ClearToEmpty();
}
inline const std::string& StreamCantonOracleServiceResponseV2::feed_id() const {
  // @@protoc_insertion_point(field_get:kaikosdk.StreamCantonOracleServiceResponseV2.feed_id)
  return _internal_feed_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void StreamCantonOracleServiceResponseV2::set_feed_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.feed_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:kaikosdk.StreamCantonOracleServiceResponseV2.feed_id)
}
inline std::string* StreamCantonOracleServiceResponseV2::mutable_feed_id() {
  std::string* _s = _internal_mutable_feed_id();
  // @@protoc_insertion_point(field_mutable:kaikosdk.StreamCantonOracleServiceResponseV2.feed_id)
  return _s;
}
inline const std::string& StreamCantonOracleServiceResponseV2::_internal_feed_id() const {
  return _impl_.feed_id_.Get();
}
inline void StreamCantonOracleServiceResponseV2::_internal_set_feed_id(const std::string& value) {
  
  _impl_.feed_id_.Set(value, GetArenaForAllocation());
}
inline std::string* StreamCantonOracleServiceResponseV2::_internal_mutable_feed_id() {
  
  return _impl_.feed_id_.Mutable(GetArenaForAllocation());
}
inline std::string* StreamCantonOracleServiceResponseV2::release_feed_id() {
  // @@protoc_insertion_point(field_release:kaikosdk.StreamCantonOracleServiceResponseV2.feed_id)
  return _impl_.feed_id_.Release();
}
inline void StreamCantonOracleServiceResponseV2::set_allocated_feed_id(std::string* feed_id) {
  if (feed_id != nullptr) {
    
  } else {
    
  }
  _impl_.feed_id_.SetAllocated(feed_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.feed_id_.IsDefault()) {
    _impl_.feed_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:kaikosdk.StreamCantonOracleServiceResponseV2.feed_id)
}

// .kaikosdk.SignedPayloadV2 payload = 4;
inline bool StreamCantonOracleServiceResponseV2::_internal_has_payload() const {
  return this != internal_default_instance() && _impl_.payload_ != nullptr;
}
inline bool StreamCantonOracleServiceResponseV2::has_payload() const {
  return _internal_has_payload();
}
inline void StreamCantonOracleServiceResponseV2::clear_payload() {
  if (GetArenaForAllocation() == nullptr && _impl_.payload_ != nullptr) {
    delete _impl_.payload_;
  }
  _impl_.payload_ = nullptr;
}
inline const ::kaikosdk::SignedPayloadV2& StreamCantonOracleServiceResponseV2::_internal_payload() const {
  const ::kaikosdk::SignedPayloadV2* p = _impl_.payload_;
  return p != nullptr ? *p : reinterpret_cast<const ::kaikosdk::SignedPayloadV2&>(
      ::kaikosdk::_SignedPayloadV2_default_instance_);
}
inline const ::kaikosdk::SignedPayloadV2& StreamCantonOracleServiceResponseV2::payload() const {
  // @@protoc_insertion_point(field_get:kaikosdk.StreamCantonOracleServiceResponseV2.payload)
  return _internal_payload();
}
inline void StreamCantonOracleServiceResponseV2::unsafe_arena_set_allocated_payload(
    ::kaikosdk::SignedPayloadV2* payload) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.payload_);
  }
  _impl_.payload_ = payload;
  if (payload) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:kaikosdk.StreamCantonOracleServiceResponseV2.payload)
}
inline ::kaikosdk::SignedPayloadV2* StreamCantonOracleServiceResponseV2::release_payload() {
  
  ::kaikosdk::SignedPayloadV2* temp = _impl_.payload_;
  _impl_.payload_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::kaikosdk::SignedPayloadV2* StreamCantonOracleServiceResponseV2::unsafe_arena_release_payload() {
  // @@protoc_insertion_point(field_release:kaikosdk.StreamCantonOracleServiceResponseV2.payload)
  
  ::kaikosdk::SignedPayloadV2* temp = _impl_.payload_;
  _impl_.payload_ = nullptr;
  return temp;
}
inline ::kaikosdk::SignedPayloadV2* StreamCantonOracleServiceResponseV2::_internal_mutable_payload() {
  
  if (_impl_.payload_ == nullptr) {
    auto* p = CreateMaybeMessage<::kaikosdk::SignedPayloadV2>(GetArenaForAllocation());
    _impl_.payload_ = p;
  }
  return _impl_.payload_;
}
inline ::kaikosdk::SignedPayloadV2* StreamCantonOracleServiceResponseV2::mutable_payload() {
  ::kaikosdk::SignedPayloadV2* _msg = _internal_mutable_payload();
  // @@protoc_insertion_point(field_mutable:kaikosdk.StreamCantonOracleServiceResponseV2.payload)
  return _msg;
}
inline void StreamCantonOracleServiceResponseV2::set_allocated_payload(::kaikosdk::SignedPayloadV2* payload) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.payload_;
  }
  if (payload) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(payload);
    if (message_arena != submessage_arena) {
      payload = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, payload, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.payload_ = payload;
  // @@protoc_insertion_point(field_set_allocated:kaikosdk.StreamCantonOracleServiceResponseV2.payload)
}

// string signature = 5;
inline void StreamCantonOracleServiceResponseV2::clear_signature() {
  _impl_.signature_.ClearToEmpty();
}
inline const std::string& StreamCantonOracleServiceResponseV2::signature() const {
  // @@protoc_insertion_point(field_get:kaikosdk.StreamCantonOracleServiceResponseV2.signature)
  return _internal_signature();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void StreamCantonOracleServiceResponseV2::set_signature(ArgT0&& arg0, ArgT... args) {
 
 _impl_.signature_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:kaikosdk.StreamCantonOracleServiceResponseV2.signature)
}
inline std::string* StreamCantonOracleServiceResponseV2::mutable_signature() {
  std::string* _s = _internal_mutable_signature();
  // @@protoc_insertion_point(field_mutable:kaikosdk.StreamCantonOracleServiceResponseV2.signature)
  return _s;
}
inline const std::string& StreamCantonOracleServiceResponseV2::_internal_signature() const {
  return _impl_.signature_.Get();
}
inline void StreamCantonOracleServiceResponseV2::_internal_set_signature(const std::string& value) {
  
  _impl_.signature_.Set(value, GetArenaForAllocation());
}
inline std::string* StreamCantonOracleServiceResponseV2::_internal_mutable_signature() {
  
  return _impl_.signature_.Mutable(GetArenaForAllocation());
}
inline std::string* StreamCantonOracleServiceResponseV2::release_signature() {
  // @@protoc_insertion_point(field_release:kaikosdk.StreamCantonOracleServiceResponseV2.signature)
  return _impl_.signature_.Release();
}
inline void StreamCantonOracleServiceResponseV2::set_allocated_signature(std::string* signature) {
  if (signature != nullptr) {
    
  } else {
    
  }
  _impl_.signature_.SetAllocated(signature, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.signature_.IsDefault()) {
    _impl_.signature_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:kaikosdk.StreamCantonOracleServiceResponseV2.signature)
}

// string canonical_hash = 6;
inline void StreamCantonOracleServiceResponseV2::clear_canonical_hash() {
  _impl_.canonical_hash_.ClearToEmpty();
}
inline const std::string& StreamCantonOracleServiceResponseV2::canonical_hash() const {
  // @@protoc_insertion_point(field_get:kaikosdk.StreamCantonOracleServiceResponseV2.canonical_hash)
  return _internal_canonical_hash();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void StreamCantonOracleServiceResponseV2::set_canonical_hash(ArgT0&& arg0, ArgT... args) {
 
 _impl_.canonical_hash_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:kaikosdk.StreamCantonOracleServiceResponseV2.canonical_hash)
}
inline std::string* StreamCantonOracleServiceResponseV2::mutable_canonical_hash() {
  std::string* _s = _internal_mutable_canonical_hash();
  // @@protoc_insertion_point(field_mutable:kaikosdk.StreamCantonOracleServiceResponseV2.canonical_hash)
  return _s;
}
inline const std::string& StreamCantonOracleServiceResponseV2::_internal_canonical_hash() const {
  return _impl_.canonical_hash_.Get();
}
inline void StreamCantonOracleServiceResponseV2::_internal_set_canonical_hash(const std::string& value) {
  
  _impl_.canonical_hash_.Set(value, GetArenaForAllocation());
}
inline std::string* StreamCantonOracleServiceResponseV2::_internal_mutable_canonical_hash() {
  
  return _impl_.canonical_hash_.Mutable(GetArenaForAllocation());
}
inline std::string* StreamCantonOracleServiceResponseV2::release_canonical_hash() {
  // @@protoc_insertion_point(field_release:kaikosdk.StreamCantonOracleServiceResponseV2.canonical_hash)
  return _impl_.canonical_hash_.Release();
}
inline void StreamCantonOracleServiceResponseV2::set_allocated_canonical_hash(std::string* canonical_hash) {
  if (canonical_hash != nullptr) {
    
  } else {
    
  }
  _impl_.canonical_hash_.SetAllocated(canonical_hash, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.canonical_hash_.IsDefault()) {
    _impl_.canonical_hash_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:kaikosdk.StreamCantonOracleServiceResponseV2.canonical_hash)
}

// .kaikosdk.VerifierContract verifier_contract = 7;
inline bool StreamCantonOracleServiceResponseV2::_internal_has_verifier_contract() const {
  return this != internal_default_instance() && _impl_.verifier_contract_ != nullptr;
}
inline bool StreamCantonOracleServiceResponseV2::has_verifier_contract() const {
  return _internal_has_verifier_contract();
}
inline void StreamCantonOracleServiceResponseV2::clear_verifier_contract() {
  if (GetArenaForAllocation() == nullptr && _impl_.verifier_contract_ != nullptr) {
    delete _impl_.verifier_contract_;
  }
  _impl_.verifier_contract_ = nullptr;
}
inline const ::kaikosdk::VerifierContract& StreamCantonOracleServiceResponseV2::_internal_verifier_contract() const {
  const ::kaikosdk::VerifierContract* p = _impl_.verifier_contract_;
  return p != nullptr ? *p : reinterpret_cast<const ::kaikosdk::VerifierContract&>(
      ::kaikosdk::_VerifierContract_default_instance_);
}
inline const ::kaikosdk::VerifierContract& StreamCantonOracleServiceResponseV2::verifier_contract() const {
  // @@protoc_insertion_point(field_get:kaikosdk.StreamCantonOracleServiceResponseV2.verifier_contract)
  return _internal_verifier_contract();
}
inline void StreamCantonOracleServiceResponseV2::unsafe_arena_set_allocated_verifier_contract(
    ::kaikosdk::VerifierContract* verifier_contract) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.verifier_contract_);
  }
  _impl_.verifier_contract_ = verifier_contract;
  if (verifier_contract) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:kaikosdk.StreamCantonOracleServiceResponseV2.verifier_contract)
}
inline ::kaikosdk::VerifierContract* StreamCantonOracleServiceResponseV2::release_verifier_contract() {
  
  ::kaikosdk::VerifierContract* temp = _impl_.verifier_contract_;
  _impl_.verifier_contract_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::kaikosdk::VerifierContract* StreamCantonOracleServiceResponseV2::unsafe_arena_release_verifier_contract() {
  // @@protoc_insertion_point(field_release:kaikosdk.StreamCantonOracleServiceResponseV2.verifier_contract)
  
  ::kaikosdk::VerifierContract* temp = _impl_.verifier_contract_;
  _impl_.verifier_contract_ = nullptr;
  return temp;
}
inline ::kaikosdk::VerifierContract* StreamCantonOracleServiceResponseV2::_internal_mutable_verifier_contract() {
  
  if (_impl_.verifier_contract_ == nullptr) {
    auto* p = CreateMaybeMessage<::kaikosdk::VerifierContract>(GetArenaForAllocation());
    _impl_.verifier_contract_ = p;
  }
  return _impl_.verifier_contract_;
}
inline ::kaikosdk::VerifierContract* StreamCantonOracleServiceResponseV2::mutable_verifier_contract() {
  ::kaikosdk::VerifierContract* _msg = _internal_mutable_verifier_contract();
  // @@protoc_insertion_point(field_mutable:kaikosdk.StreamCantonOracleServiceResponseV2.verifier_contract)
  return _msg;
}
inline void StreamCantonOracleServiceResponseV2::set_allocated_verifier_contract(::kaikosdk::VerifierContract* verifier_contract) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.verifier_contract_;
  }
  if (verifier_contract) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(verifier_contract);
    if (message_arena != submessage_arena) {
      verifier_contract = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, verifier_contract, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.verifier_contract_ = verifier_contract;
  // @@protoc_insertion_point(field_set_allocated:kaikosdk.StreamCantonOracleServiceResponseV2.verifier_contract)
}

// -------------------------------------------------------------------

// VerifierContract

// string templateId = 1;
inline void VerifierContract::clear_templateid() {
  _impl_.templateid_.ClearToEmpty();
}
inline const std::string& VerifierContract::templateid() const {
  // @@protoc_insertion_point(field_get:kaikosdk.VerifierContract.templateId)
  return _internal_templateid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void VerifierContract::set_templateid(ArgT0&& arg0, ArgT... args) {
 
 _impl_.templateid_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:kaikosdk.VerifierContract.templateId)
}
inline std::string* VerifierContract::mutable_templateid() {
  std::string* _s = _internal_mutable_templateid();
  // @@protoc_insertion_point(field_mutable:kaikosdk.VerifierContract.templateId)
  return _s;
}
inline const std::string& VerifierContract::_internal_templateid() const {
  return _impl_.templateid_.Get();
}
inline void VerifierContract::_internal_set_templateid(const std::string& value) {
  
  _impl_.templateid_.Set(value, GetArenaForAllocation());
}
inline std::string* VerifierContract::_internal_mutable_templateid() {
  
  return _impl_.templateid_.Mutable(GetArenaForAllocation());
}
inline std::string* VerifierContract::release_templateid() {
  // @@protoc_insertion_point(field_release:kaikosdk.VerifierContract.templateId)
  return _impl_.templateid_.Release();
}
inline void VerifierContract::set_allocated_templateid(std::string* templateid) {
  if (templateid != nullptr) {
    
  } else {
    
  }
  _impl_.templateid_.SetAllocated(templateid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.templateid_.IsDefault()) {
    _impl_.templateid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:kaikosdk.VerifierContract.templateId)
}

// string contractId = 2;
inline void VerifierContract::clear_contractid() {
  _impl_.contractid_.ClearToEmpty();
}
inline const std::string& VerifierContract::contractid() const {
  // @@protoc_insertion_point(field_get:kaikosdk.VerifierContract.contractId)
  return _internal_contractid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void VerifierContract::set_contractid(ArgT0&& arg0, ArgT... args) {
 
 _impl_.contractid_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:kaikosdk.VerifierContract.contractId)
}
inline std::string* VerifierContract::mutable_contractid() {
  std::string* _s = _internal_mutable_contractid();
  // @@protoc_insertion_point(field_mutable:kaikosdk.VerifierContract.contractId)
  return _s;
}
inline const std::string& VerifierContract::_internal_contractid() const {
  return _impl_.contractid_.Get();
}
inline void VerifierContract::_internal_set_contractid(const std::string& value) {
  
  _impl_.contractid_.Set(value, GetArenaForAllocation());
}
inline std::string* VerifierContract::_internal_mutable_contractid() {
  
  return _impl_.contractid_.Mutable(GetArenaForAllocation());
}
inline std::string* VerifierContract::release_contractid() {
  // @@protoc_insertion_point(field_release:kaikosdk.VerifierContract.contractId)
  return _impl_.contractid_.Release();
}
inline void VerifierContract::set_allocated_contractid(std::string* contractid) {
  if (contractid != nullptr) {
    
  } else {
    
  }
  _impl_.contractid_.SetAllocated(contractid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.contractid_.IsDefault()) {
    _impl_.contractid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:kaikosdk.VerifierContract.contractId)
}

// string createdEventBlob = 3;
inline void VerifierContract::clear_createdeventblob() {
  _impl_.createdeventblob_.ClearToEmpty();
}
inline const std::string& VerifierContract::createdeventblob() const {
  // @@protoc_insertion_point(field_get:kaikosdk.VerifierContract.createdEventBlob)
  return _internal_createdeventblob();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void VerifierContract::set_createdeventblob(ArgT0&& arg0, ArgT... args) {
 
 _impl_.createdeventblob_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:kaikosdk.VerifierContract.createdEventBlob)
}
inline std::string* VerifierContract::mutable_createdeventblob() {
  std::string* _s = _internal_mutable_createdeventblob();
  // @@protoc_insertion_point(field_mutable:kaikosdk.VerifierContract.createdEventBlob)
  return _s;
}
inline const std::string& VerifierContract::_internal_createdeventblob() const {
  return _impl_.createdeventblob_.Get();
}
inline void VerifierContract::_internal_set_createdeventblob(const std::string& value) {
  
  _impl_.createdeventblob_.Set(value, GetArenaForAllocation());
}
inline std::string* VerifierContract::_internal_mutable_createdeventblob() {
  
  return _impl_.createdeventblob_.Mutable(GetArenaForAllocation());
}
inline std::string* VerifierContract::release_createdeventblob() {
  // @@protoc_insertion_point(field_release:kaikosdk.VerifierContract.createdEventBlob)
  return _impl_.createdeventblob_.Release();
}
inline void VerifierContract::set_allocated_createdeventblob(std::string* createdeventblob) {
  if (createdeventblob != nullptr) {
    
  } else {
    
  }
  _impl_.createdeventblob_.SetAllocated(createdeventblob, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.createdeventblob_.IsDefault()) {
    _impl_.createdeventblob_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:kaikosdk.VerifierContract.createdEventBlob)
}

// -------------------------------------------------------------------

// SignedPayloadV2

// string publishedAt = 1;
inline void SignedPayloadV2::clear_publishedat() {
  _impl_.publishedat_.ClearToEmpty();
}
inline const std::string& SignedPayloadV2::publishedat() const {
  // @@protoc_insertion_point(field_get:kaikosdk.SignedPayloadV2.publishedAt)
  return _internal_publishedat();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SignedPayloadV2::set_publishedat(ArgT0&& arg0, ArgT... args) {
 
 _impl_.publishedat_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:kaikosdk.SignedPayloadV2.publishedAt)
}
inline std::string* SignedPayloadV2::mutable_publishedat() {
  std::string* _s = _internal_mutable_publishedat();
  // @@protoc_insertion_point(field_mutable:kaikosdk.SignedPayloadV2.publishedAt)
  return _s;
}
inline const std::string& SignedPayloadV2::_internal_publishedat() const {
  return _impl_.publishedat_.Get();
}
inline void SignedPayloadV2::_internal_set_publishedat(const std::string& value) {
  
  _impl_.publishedat_.Set(value, GetArenaForAllocation());
}
inline std::string* SignedPayloadV2::_internal_mutable_publishedat() {
  
  return _impl_.publishedat_.Mutable(GetArenaForAllocation());
}
inline std::string* SignedPayloadV2::release_publishedat() {
  // @@protoc_insertion_point(field_release:kaikosdk.SignedPayloadV2.publishedAt)
  return _impl_.publishedat_.Release();
}
inline void SignedPayloadV2::set_allocated_publishedat(std::string* publishedat) {
  if (publishedat != nullptr) {
    
  } else {
    
  }
  _impl_.publishedat_.SetAllocated(publishedat, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.publishedat_.IsDefault()) {
    _impl_.publishedat_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:kaikosdk.SignedPayloadV2.publishedAt)
}

// string expiresAt = 2;
inline void SignedPayloadV2::clear_expiresat() {
  _impl_.expiresat_.ClearToEmpty();
}
inline const std::string& SignedPayloadV2::expiresat() const {
  // @@protoc_insertion_point(field_get:kaikosdk.SignedPayloadV2.expiresAt)
  return _internal_expiresat();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SignedPayloadV2::set_expiresat(ArgT0&& arg0, ArgT... args) {
 
 _impl_.expiresat_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:kaikosdk.SignedPayloadV2.expiresAt)
}
inline std::string* SignedPayloadV2::mutable_expiresat() {
  std::string* _s = _internal_mutable_expiresat();
  // @@protoc_insertion_point(field_mutable:kaikosdk.SignedPayloadV2.expiresAt)
  return _s;
}
inline const std::string& SignedPayloadV2::_internal_expiresat() const {
  return _impl_.expiresat_.Get();
}
inline void SignedPayloadV2::_internal_set_expiresat(const std::string& value) {
  
  _impl_.expiresat_.Set(value, GetArenaForAllocation());
}
inline std::string* SignedPayloadV2::_internal_mutable_expiresat() {
  
  return _impl_.expiresat_.Mutable(GetArenaForAllocation());
}
inline std::string* SignedPayloadV2::release_expiresat() {
  // @@protoc_insertion_point(field_release:kaikosdk.SignedPayloadV2.expiresAt)
  return _impl_.expiresat_.Release();
}
inline void SignedPayloadV2::set_allocated_expiresat(std::string* expiresat) {
  if (expiresat != nullptr) {
    
  } else {
    
  }
  _impl_.expiresat_.SetAllocated(expiresat, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.expiresat_.IsDefault()) {
    _impl_.expiresat_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:kaikosdk.SignedPayloadV2.expiresAt)
}

// optional .kaikosdk.CostV2 cost = 3;
inline bool SignedPayloadV2::_internal_has_cost() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.cost_ != nullptr);
  return value;
}
inline bool SignedPayloadV2::has_cost() const {
  return _internal_has_cost();
}
inline void SignedPayloadV2::clear_cost() {
  if (_impl_.cost_ != nullptr) _impl_.cost_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::kaikosdk::CostV2& SignedPayloadV2::_internal_cost() const {
  const ::kaikosdk::CostV2* p = _impl_.cost_;
  return p != nullptr ? *p : reinterpret_cast<const ::kaikosdk::CostV2&>(
      ::kaikosdk::_CostV2_default_instance_);
}
inline const ::kaikosdk::CostV2& SignedPayloadV2::cost() const {
  // @@protoc_insertion_point(field_get:kaikosdk.SignedPayloadV2.cost)
  return _internal_cost();
}
inline void SignedPayloadV2::unsafe_arena_set_allocated_cost(
    ::kaikosdk::CostV2* cost) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.cost_);
  }
  _impl_.cost_ = cost;
  if (cost) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:kaikosdk.SignedPayloadV2.cost)
}
inline ::kaikosdk::CostV2* SignedPayloadV2::release_cost() {
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::kaikosdk::CostV2* temp = _impl_.cost_;
  _impl_.cost_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::kaikosdk::CostV2* SignedPayloadV2::unsafe_arena_release_cost() {
  // @@protoc_insertion_point(field_release:kaikosdk.SignedPayloadV2.cost)
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::kaikosdk::CostV2* temp = _impl_.cost_;
  _impl_.cost_ = nullptr;
  return temp;
}
inline ::kaikosdk::CostV2* SignedPayloadV2::_internal_mutable_cost() {
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.cost_ == nullptr) {
    auto* p = CreateMaybeMessage<::kaikosdk::CostV2>(GetArenaForAllocation());
    _impl_.cost_ = p;
  }
  return _impl_.cost_;
}
inline ::kaikosdk::CostV2* SignedPayloadV2::mutable_cost() {
  ::kaikosdk::CostV2* _msg = _internal_mutable_cost();
  // @@protoc_insertion_point(field_mutable:kaikosdk.SignedPayloadV2.cost)
  return _msg;
}
inline void SignedPayloadV2::set_allocated_cost(::kaikosdk::CostV2* cost) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.cost_;
  }
  if (cost) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(cost);
    if (message_arena != submessage_arena) {
      cost = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, cost, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.cost_ = cost;
  // @@protoc_insertion_point(field_set_allocated:kaikosdk.SignedPayloadV2.cost)
}

// .kaikosdk.QuoteV2 quote = 4;
inline bool SignedPayloadV2::_internal_has_quote() const {
  return this != internal_default_instance() && _impl_.quote_ != nullptr;
}
inline bool SignedPayloadV2::has_quote() const {
  return _internal_has_quote();
}
inline void SignedPayloadV2::clear_quote() {
  if (GetArenaForAllocation() == nullptr && _impl_.quote_ != nullptr) {
    delete _impl_.quote_;
  }
  _impl_.quote_ = nullptr;
}
inline const ::kaikosdk::QuoteV2& SignedPayloadV2::_internal_quote() const {
  const ::kaikosdk::QuoteV2* p = _impl_.quote_;
  return p != nullptr ? *p : reinterpret_cast<const ::kaikosdk::QuoteV2&>(
      ::kaikosdk::_QuoteV2_default_instance_);
}
inline const ::kaikosdk::QuoteV2& SignedPayloadV2::quote() const {
  // @@protoc_insertion_point(field_get:kaikosdk.SignedPayloadV2.quote)
  return _internal_quote();
}
inline void SignedPayloadV2::unsafe_arena_set_allocated_quote(
    ::kaikosdk::QuoteV2* quote) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.quote_);
  }
  _impl_.quote_ = quote;
  if (quote) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:kaikosdk.SignedPayloadV2.quote)
}
inline ::kaikosdk::QuoteV2* SignedPayloadV2::release_quote() {
  
  ::kaikosdk::QuoteV2* temp = _impl_.quote_;
  _impl_.quote_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::kaikosdk::QuoteV2* SignedPayloadV2::unsafe_arena_release_quote() {
  // @@protoc_insertion_point(field_release:kaikosdk.SignedPayloadV2.quote)
  
  ::kaikosdk::QuoteV2* temp = _impl_.quote_;
  _impl_.quote_ = nullptr;
  return temp;
}
inline ::kaikosdk::QuoteV2* SignedPayloadV2::_internal_mutable_quote() {
  
  if (_impl_.quote_ == nullptr) {
    auto* p = CreateMaybeMessage<::kaikosdk::QuoteV2>(GetArenaForAllocation());
    _impl_.quote_ = p;
  }
  return _impl_.quote_;
}
inline ::kaikosdk::QuoteV2* SignedPayloadV2::mutable_quote() {
  ::kaikosdk::QuoteV2* _msg = _internal_mutable_quote();
  // @@protoc_insertion_point(field_mutable:kaikosdk.SignedPayloadV2.quote)
  return _msg;
}
inline void SignedPayloadV2::set_allocated_quote(::kaikosdk::QuoteV2* quote) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.quote_;
  }
  if (quote) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(quote);
    if (message_arena != submessage_arena) {
      quote = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, quote, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.quote_ = quote;
  // @@protoc_insertion_point(field_set_allocated:kaikosdk.SignedPayloadV2.quote)
}

// string payee = 5;
inline void SignedPayloadV2::clear_payee() {
  _impl_.payee_.ClearToEmpty();
}
inline const std::string& SignedPayloadV2::payee() const {
  // @@protoc_insertion_point(field_get:kaikosdk.SignedPayloadV2.payee)
  return _internal_payee();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SignedPayloadV2::set_payee(ArgT0&& arg0, ArgT... args) {
 
 _impl_.payee_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:kaikosdk.SignedPayloadV2.payee)
}
inline std::string* SignedPayloadV2::mutable_payee() {
  std::string* _s = _internal_mutable_payee();
  // @@protoc_insertion_point(field_mutable:kaikosdk.SignedPayloadV2.payee)
  return _s;
}
inline const std::string& SignedPayloadV2::_internal_payee() const {
  return _impl_.payee_.Get();
}
inline void SignedPayloadV2::_internal_set_payee(const std::string& value) {
  
  _impl_.payee_.Set(value, GetArenaForAllocation());
}
inline std::string* SignedPayloadV2::_internal_mutable_payee() {
  
  return _impl_.payee_.Mutable(GetArenaForAllocation());
}
inline std::string* SignedPayloadV2::release_payee() {
  // @@protoc_insertion_point(field_release:kaikosdk.SignedPayloadV2.payee)
  return _impl_.payee_.Release();
}
inline void SignedPayloadV2::set_allocated_payee(std::string* payee) {
  if (payee != nullptr) {
    
  } else {
    
  }
  _impl_.payee_.SetAllocated(payee, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.payee_.IsDefault()) {
    _impl_.payee_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:kaikosdk.SignedPayloadV2.payee)
}

// -------------------------------------------------------------------

// CostV2

// string fee = 1;
inline void CostV2::clear_fee() {
  _impl_.fee_.ClearToEmpty();
}
inline const std::string& CostV2::fee() const {
  // @@protoc_insertion_point(field_get:kaikosdk.CostV2.fee)
  return _internal_fee();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CostV2::set_fee(ArgT0&& arg0, ArgT... args) {
 
 _impl_.fee_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:kaikosdk.CostV2.fee)
}
inline std::string* CostV2::mutable_fee() {
  std::string* _s = _internal_mutable_fee();
  // @@protoc_insertion_point(field_mutable:kaikosdk.CostV2.fee)
  return _s;
}
inline const std::string& CostV2::_internal_fee() const {
  return _impl_.fee_.Get();
}
inline void CostV2::_internal_set_fee(const std::string& value) {
  
  _impl_.fee_.Set(value, GetArenaForAllocation());
}
inline std::string* CostV2::_internal_mutable_fee() {
  
  return _impl_.fee_.Mutable(GetArenaForAllocation());
}
inline std::string* CostV2::release_fee() {
  // @@protoc_insertion_point(field_release:kaikosdk.CostV2.fee)
  return _impl_.fee_.Release();
}
inline void CostV2::set_allocated_fee(std::string* fee) {
  if (fee != nullptr) {
    
  } else {
    
  }
  _impl_.fee_.SetAllocated(fee, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.fee_.IsDefault()) {
    _impl_.fee_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:kaikosdk.CostV2.fee)
}

// .kaikosdk.InstrumentIdV2 instrument = 2;
inline bool CostV2::_internal_has_instrument() const {
  return this != internal_default_instance() && _impl_.instrument_ != nullptr;
}
inline bool CostV2::has_instrument() const {
  return _internal_has_instrument();
}
inline void CostV2::clear_instrument() {
  if (GetArenaForAllocation() == nullptr && _impl_.instrument_ != nullptr) {
    delete _impl_.instrument_;
  }
  _impl_.instrument_ = nullptr;
}
inline const ::kaikosdk::InstrumentIdV2& CostV2::_internal_instrument() const {
  const ::kaikosdk::InstrumentIdV2* p = _impl_.instrument_;
  return p != nullptr ? *p : reinterpret_cast<const ::kaikosdk::InstrumentIdV2&>(
      ::kaikosdk::_InstrumentIdV2_default_instance_);
}
inline const ::kaikosdk::InstrumentIdV2& CostV2::instrument() const {
  // @@protoc_insertion_point(field_get:kaikosdk.CostV2.instrument)
  return _internal_instrument();
}
inline void CostV2::unsafe_arena_set_allocated_instrument(
    ::kaikosdk::InstrumentIdV2* instrument) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.instrument_);
  }
  _impl_.instrument_ = instrument;
  if (instrument) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:kaikosdk.CostV2.instrument)
}
inline ::kaikosdk::InstrumentIdV2* CostV2::release_instrument() {
  
  ::kaikosdk::InstrumentIdV2* temp = _impl_.instrument_;
  _impl_.instrument_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::kaikosdk::InstrumentIdV2* CostV2::unsafe_arena_release_instrument() {
  // @@protoc_insertion_point(field_release:kaikosdk.CostV2.instrument)
  
  ::kaikosdk::InstrumentIdV2* temp = _impl_.instrument_;
  _impl_.instrument_ = nullptr;
  return temp;
}
inline ::kaikosdk::InstrumentIdV2* CostV2::_internal_mutable_instrument() {
  
  if (_impl_.instrument_ == nullptr) {
    auto* p = CreateMaybeMessage<::kaikosdk::InstrumentIdV2>(GetArenaForAllocation());
    _impl_.instrument_ = p;
  }
  return _impl_.instrument_;
}
inline ::kaikosdk::InstrumentIdV2* CostV2::mutable_instrument() {
  ::kaikosdk::InstrumentIdV2* _msg = _internal_mutable_instrument();
  // @@protoc_insertion_point(field_mutable:kaikosdk.CostV2.instrument)
  return _msg;
}
inline void CostV2::set_allocated_instrument(::kaikosdk::InstrumentIdV2* instrument) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.instrument_;
  }
  if (instrument) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(instrument);
    if (message_arena != submessage_arena) {
      instrument = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, instrument, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.instrument_ = instrument;
  // @@protoc_insertion_point(field_set_allocated:kaikosdk.CostV2.instrument)
}

// -------------------------------------------------------------------

// InstrumentIdV2

// string admin = 1;
inline void InstrumentIdV2::clear_admin() {
  _impl_.admin_.ClearToEmpty();
}
inline const std::string& InstrumentIdV2::admin() const {
  // @@protoc_insertion_point(field_get:kaikosdk.InstrumentIdV2.admin)
  return _internal_admin();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void InstrumentIdV2::set_admin(ArgT0&& arg0, ArgT... args) {
 
 _impl_.admin_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:kaikosdk.InstrumentIdV2.admin)
}
inline std::string* InstrumentIdV2::mutable_admin() {
  std::string* _s = _internal_mutable_admin();
  // @@protoc_insertion_point(field_mutable:kaikosdk.InstrumentIdV2.admin)
  return _s;
}
inline const std::string& InstrumentIdV2::_internal_admin() const {
  return _impl_.admin_.Get();
}
inline void InstrumentIdV2::_internal_set_admin(const std::string& value) {
  
  _impl_.admin_.Set(value, GetArenaForAllocation());
}
inline std::string* InstrumentIdV2::_internal_mutable_admin() {
  
  return _impl_.admin_.Mutable(GetArenaForAllocation());
}
inline std::string* InstrumentIdV2::release_admin() {
  // @@protoc_insertion_point(field_release:kaikosdk.InstrumentIdV2.admin)
  return _impl_.admin_.Release();
}
inline void InstrumentIdV2::set_allocated_admin(std::string* admin) {
  if (admin != nullptr) {
    
  } else {
    
  }
  _impl_.admin_.SetAllocated(admin, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.admin_.IsDefault()) {
    _impl_.admin_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:kaikosdk.InstrumentIdV2.admin)
}

// string id = 2;
inline void InstrumentIdV2::clear_id() {
  _impl_.id_.ClearToEmpty();
}
inline const std::string& InstrumentIdV2::id() const {
  // @@protoc_insertion_point(field_get:kaikosdk.InstrumentIdV2.id)
  return _internal_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void InstrumentIdV2::set_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:kaikosdk.InstrumentIdV2.id)
}
inline std::string* InstrumentIdV2::mutable_id() {
  std::string* _s = _internal_mutable_id();
  // @@protoc_insertion_point(field_mutable:kaikosdk.InstrumentIdV2.id)
  return _s;
}
inline const std::string& InstrumentIdV2::_internal_id() const {
  return _impl_.id_.Get();
}
inline void InstrumentIdV2::_internal_set_id(const std::string& value) {
  
  _impl_.id_.Set(value, GetArenaForAllocation());
}
inline std::string* InstrumentIdV2::_internal_mutable_id() {
  
  return _impl_.id_.Mutable(GetArenaForAllocation());
}
inline std::string* InstrumentIdV2::release_id() {
  // @@protoc_insertion_point(field_release:kaikosdk.InstrumentIdV2.id)
  return _impl_.id_.Release();
}
inline void InstrumentIdV2::set_allocated_id(std::string* id) {
  if (id != nullptr) {
    
  } else {
    
  }
  _impl_.id_.SetAllocated(id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.id_.IsDefault()) {
    _impl_.id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:kaikosdk.InstrumentIdV2.id)
}

// -------------------------------------------------------------------

// QuoteV2

// string feedId = 1;
inline void QuoteV2::clear_feedid() {
  _impl_.feedid_.ClearToEmpty();
}
inline const std::string& QuoteV2::feedid() const {
  // @@protoc_insertion_point(field_get:kaikosdk.QuoteV2.feedId)
  return _internal_feedid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void QuoteV2::set_feedid(ArgT0&& arg0, ArgT... args) {
 
 _impl_.feedid_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:kaikosdk.QuoteV2.feedId)
}
inline std::string* QuoteV2::mutable_feedid() {
  std::string* _s = _internal_mutable_feedid();
  // @@protoc_insertion_point(field_mutable:kaikosdk.QuoteV2.feedId)
  return _s;
}
inline const std::string& QuoteV2::_internal_feedid() const {
  return _impl_.feedid_.Get();
}
inline void QuoteV2::_internal_set_feedid(const std::string& value) {
  
  _impl_.feedid_.Set(value, GetArenaForAllocation());
}
inline std::string* QuoteV2::_internal_mutable_feedid() {
  
  return _impl_.feedid_.Mutable(GetArenaForAllocation());
}
inline std::string* QuoteV2::release_feedid() {
  // @@protoc_insertion_point(field_release:kaikosdk.QuoteV2.feedId)
  return _impl_.feedid_.Release();
}
inline void QuoteV2::set_allocated_feedid(std::string* feedid) {
  if (feedid != nullptr) {
    
  } else {
    
  }
  _impl_.feedid_.SetAllocated(feedid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.feedid_.IsDefault()) {
    _impl_.feedid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:kaikosdk.QuoteV2.feedId)
}

// string price = 2;
inline void QuoteV2::clear_price() {
  _impl_.price_.ClearToEmpty();
}
inline const std::string& QuoteV2::price() const {
  // @@protoc_insertion_point(field_get:kaikosdk.QuoteV2.price)
  return _internal_price();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void QuoteV2::set_price(ArgT0&& arg0, ArgT... args) {
 
 _impl_.price_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:kaikosdk.QuoteV2.price)
}
inline std::string* QuoteV2::mutable_price() {
  std::string* _s = _internal_mutable_price();
  // @@protoc_insertion_point(field_mutable:kaikosdk.QuoteV2.price)
  return _s;
}
inline const std::string& QuoteV2::_internal_price() const {
  return _impl_.price_.Get();
}
inline void QuoteV2::_internal_set_price(const std::string& value) {
  
  _impl_.price_.Set(value, GetArenaForAllocation());
}
inline std::string* QuoteV2::_internal_mutable_price() {
  
  return _impl_.price_.Mutable(GetArenaForAllocation());
}
inline std::string* QuoteV2::release_price() {
  // @@protoc_insertion_point(field_release:kaikosdk.QuoteV2.price)
  return _impl_.price_.Release();
}
inline void QuoteV2::set_allocated_price(std::string* price) {
  if (price != nullptr) {
    
  } else {
    
  }
  _impl_.price_.SetAllocated(price, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.price_.IsDefault()) {
    _impl_.price_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:kaikosdk.QuoteV2.price)
}

// string priceTime = 3;
inline void QuoteV2::clear_pricetime() {
  _impl_.pricetime_.ClearToEmpty();
}
inline const std::string& QuoteV2::pricetime() const {
  // @@protoc_insertion_point(field_get:kaikosdk.QuoteV2.priceTime)
  return _internal_pricetime();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void QuoteV2::set_pricetime(ArgT0&& arg0, ArgT... args) {
 
 _impl_.pricetime_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:kaikosdk.QuoteV2.priceTime)
}
inline std::string* QuoteV2::mutable_pricetime() {
  std::string* _s = _internal_mutable_pricetime();
  // @@protoc_insertion_point(field_mutable:kaikosdk.QuoteV2.priceTime)
  return _s;
}
inline const std::string& QuoteV2::_internal_pricetime() const {
  return _impl_.pricetime_.Get();
}
inline void QuoteV2::_internal_set_pricetime(const std::string& value) {
  
  _impl_.pricetime_.Set(value, GetArenaForAllocation());
}
inline std::string* QuoteV2::_internal_mutable_pricetime() {
  
  return _impl_.pricetime_.Mutable(GetArenaForAllocation());
}
inline std::string* QuoteV2::release_pricetime() {
  // @@protoc_insertion_point(field_release:kaikosdk.QuoteV2.priceTime)
  return _impl_.pricetime_.Release();
}
inline void QuoteV2::set_allocated_pricetime(std::string* pricetime) {
  if (pricetime != nullptr) {
    
  } else {
    
  }
  _impl_.pricetime_.SetAllocated(pricetime, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.pricetime_.IsDefault()) {
    _impl_.pricetime_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:kaikosdk.QuoteV2.priceTime)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace kaikosdk

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_sdk_2fstream_2fcanton_5foracle_5fv2_2fresponse_2eproto
