// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk/stream/canton_oracle_v1/response.proto

#include "sdk/stream/canton_oracle_v1/response.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace kaikosdk {
PROTOBUF_CONSTEXPR StreamCantonOracleServiceResponseV1::StreamCantonOracleServiceResponseV1(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.data_)*/nullptr
  , /*decltype(_impl_.canton_oracle_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct StreamCantonOracleServiceResponseV1DefaultTypeInternal {
  PROTOBUF_CONSTEXPR StreamCantonOracleServiceResponseV1DefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~StreamCantonOracleServiceResponseV1DefaultTypeInternal() {}
  union {
    StreamCantonOracleServiceResponseV1 _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StreamCantonOracleServiceResponseV1DefaultTypeInternal _StreamCantonOracleServiceResponseV1_default_instance_;
PROTOBUF_CONSTEXPR CantonOracleDataV1::CantonOracleDataV1(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.signature_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.value_)*/int64_t{0}
  , /*decltype(_impl_.timestamp_)*/int64_t{0}
  , /*decltype(_impl_.decimal_)*/0} {}
struct CantonOracleDataV1DefaultTypeInternal {
  PROTOBUF_CONSTEXPR CantonOracleDataV1DefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CantonOracleDataV1DefaultTypeInternal() {}
  union {
    CantonOracleDataV1 _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CantonOracleDataV1DefaultTypeInternal _CantonOracleDataV1_default_instance_;
PROTOBUF_CONSTEXPR CantonOraclePayloadV1::CantonOraclePayloadV1(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.template_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.contract_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.synchronizer_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.created_event_blob_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CantonOraclePayloadV1DefaultTypeInternal {
  PROTOBUF_CONSTEXPR CantonOraclePayloadV1DefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CantonOraclePayloadV1DefaultTypeInternal() {}
  union {
    CantonOraclePayloadV1 _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CantonOraclePayloadV1DefaultTypeInternal _CantonOraclePayloadV1_default_instance_;
}  // namespace kaikosdk
static ::_pb::Metadata file_level_metadata_sdk_2fstream_2fcanton_5foracle_5fv1_2fresponse_2eproto[3];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_sdk_2fstream_2fcanton_5foracle_5fv1_2fresponse_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_sdk_2fstream_2fcanton_5foracle_5fv1_2fresponse_2eproto = nullptr;

const uint32_t TableStruct_sdk_2fstream_2fcanton_5foracle_5fv1_2fresponse_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::kaikosdk::StreamCantonOracleServiceResponseV1, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::kaikosdk::StreamCantonOracleServiceResponseV1, _impl_.data_),
  PROTOBUF_FIELD_OFFSET(::kaikosdk::StreamCantonOracleServiceResponseV1, _impl_.canton_oracle_),
  PROTOBUF_FIELD_OFFSET(::kaikosdk::CantonOracleDataV1, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::kaikosdk::CantonOracleDataV1, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::kaikosdk::CantonOracleDataV1, _impl_.name_),
  PROTOBUF_FIELD_OFFSET(::kaikosdk::CantonOracleDataV1, _impl_.value_),
  PROTOBUF_FIELD_OFFSET(::kaikosdk::CantonOracleDataV1, _impl_.decimal_),
  PROTOBUF_FIELD_OFFSET(::kaikosdk::CantonOracleDataV1, _impl_.timestamp_),
  PROTOBUF_FIELD_OFFSET(::kaikosdk::CantonOracleDataV1, _impl_.signature_),
  ~0u,
  0,
  ~0u,
  ~0u,
  ~0u,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::kaikosdk::CantonOraclePayloadV1, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::kaikosdk::CantonOraclePayloadV1, _impl_.template_id_),
  PROTOBUF_FIELD_OFFSET(::kaikosdk::CantonOraclePayloadV1, _impl_.contract_id_),
  PROTOBUF_FIELD_OFFSET(::kaikosdk::CantonOraclePayloadV1, _impl_.synchronizer_id_),
  PROTOBUF_FIELD_OFFSET(::kaikosdk::CantonOraclePayloadV1, _impl_.created_event_blob_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::kaikosdk::StreamCantonOracleServiceResponseV1)},
  { 8, 19, -1, sizeof(::kaikosdk::CantonOracleDataV1)},
  { 24, -1, -1, sizeof(::kaikosdk::CantonOraclePayloadV1)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::kaikosdk::_StreamCantonOracleServiceResponseV1_default_instance_._instance,
  &::kaikosdk::_CantonOracleDataV1_default_instance_._instance,
  &::kaikosdk::_CantonOraclePayloadV1_default_instance_._instance,
};

const char descriptor_table_protodef_sdk_2fstream_2fcanton_5foracle_5fv1_2fresponse_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n*sdk/stream/canton_oracle_v1/response.p"
  "roto\022\010kaikosdk\"\211\001\n#StreamCantonOracleSer"
  "viceResponseV1\022*\n\004data\030\001 \001(\0132\034.kaikosdk."
  "CantonOracleDataV1\0226\n\rcanton_oracle\030\002 \001("
  "\0132\037.kaikosdk.CantonOraclePayloadV1\"w\n\022Ca"
  "ntonOracleDataV1\022\014\n\004name\030\001 \001(\t\022\022\n\005value\030"
  "\002 \001(\003H\000\210\001\001\022\017\n\007decimal\030\003 \001(\005\022\021\n\ttimestamp"
  "\030\004 \001(\003\022\021\n\tsignature\030\005 \001(\tB\010\n\006_value\"v\n\025C"
  "antonOraclePayloadV1\022\023\n\013template_id\030\001 \001("
  "\t\022\023\n\013contract_id\030\002 \001(\t\022\027\n\017synchronizer_i"
  "d\030\003 \001(\t\022\032\n\022created_event_blob\030\004 \001(\tB\226\001\n%"
  "com.kaiko.sdk.stream.canton_oracle_v1P\001Z"
  "Jgithub.com/kaikodata/kaiko-go-sdk/strea"
  "m/canton_oracle_v1;canton_oracle_v1\252\002\036Ka"
  "ikoSdk.Stream.CantonOracleV1b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_sdk_2fstream_2fcanton_5foracle_5fv1_2fresponse_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_sdk_2fstream_2fcanton_5foracle_5fv1_2fresponse_2eproto = {
    false, false, 596, descriptor_table_protodef_sdk_2fstream_2fcanton_5foracle_5fv1_2fresponse_2eproto,
    "sdk/stream/canton_oracle_v1/response.proto",
    &descriptor_table_sdk_2fstream_2fcanton_5foracle_5fv1_2fresponse_2eproto_once, nullptr, 0, 3,
    schemas, file_default_instances, TableStruct_sdk_2fstream_2fcanton_5foracle_5fv1_2fresponse_2eproto::offsets,
    file_level_metadata_sdk_2fstream_2fcanton_5foracle_5fv1_2fresponse_2eproto, file_level_enum_descriptors_sdk_2fstream_2fcanton_5foracle_5fv1_2fresponse_2eproto,
    file_level_service_descriptors_sdk_2fstream_2fcanton_5foracle_5fv1_2fresponse_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_sdk_2fstream_2fcanton_5foracle_5fv1_2fresponse_2eproto_getter() {
  return &descriptor_table_sdk_2fstream_2fcanton_5foracle_5fv1_2fresponse_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_sdk_2fstream_2fcanton_5foracle_5fv1_2fresponse_2eproto(&descriptor_table_sdk_2fstream_2fcanton_5foracle_5fv1_2fresponse_2eproto);
namespace kaikosdk {

// ===================================================================

class StreamCantonOracleServiceResponseV1::_Internal {
 public:
  static const ::kaikosdk::CantonOracleDataV1& data(const StreamCantonOracleServiceResponseV1* msg);
  static const ::kaikosdk::CantonOraclePayloadV1& canton_oracle(const StreamCantonOracleServiceResponseV1* msg);
};

const ::kaikosdk::CantonOracleDataV1&
StreamCantonOracleServiceResponseV1::_Internal::data(const StreamCantonOracleServiceResponseV1* msg) {
  return *msg->_impl_.data_;
}
const ::kaikosdk::CantonOraclePayloadV1&
StreamCantonOracleServiceResponseV1::_Internal::canton_oracle(const StreamCantonOracleServiceResponseV1* msg) {
  return *msg->_impl_.canton_oracle_;
}
StreamCantonOracleServiceResponseV1::StreamCantonOracleServiceResponseV1(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:kaikosdk.StreamCantonOracleServiceResponseV1)
}
StreamCantonOracleServiceResponseV1::StreamCantonOracleServiceResponseV1(const StreamCantonOracleServiceResponseV1& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  StreamCantonOracleServiceResponseV1* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.data_){nullptr}
    , decltype(_impl_.canton_oracle_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_data()) {
    _this->_impl_.data_ = new ::kaikosdk::CantonOracleDataV1(*from._impl_.data_);
  }
  if (from._internal_has_canton_oracle()) {
    _this->_impl_.canton_oracle_ = new ::kaikosdk::CantonOraclePayloadV1(*from._impl_.canton_oracle_);
  }
  // @@protoc_insertion_point(copy_constructor:kaikosdk.StreamCantonOracleServiceResponseV1)
}

inline void StreamCantonOracleServiceResponseV1::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.data_){nullptr}
    , decltype(_impl_.canton_oracle_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

StreamCantonOracleServiceResponseV1::~StreamCantonOracleServiceResponseV1() {
  // @@protoc_insertion_point(destructor:kaikosdk.StreamCantonOracleServiceResponseV1)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void StreamCantonOracleServiceResponseV1::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.data_;
  if (this != internal_default_instance()) delete _impl_.canton_oracle_;
}

void StreamCantonOracleServiceResponseV1::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void StreamCantonOracleServiceResponseV1::Clear() {
// @@protoc_insertion_point(message_clear_start:kaikosdk.StreamCantonOracleServiceResponseV1)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.data_ != nullptr) {
    delete _impl_.data_;
  }
  _impl_.data_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.canton_oracle_ != nullptr) {
    delete _impl_.canton_oracle_;
  }
  _impl_.canton_oracle_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* StreamCantonOracleServiceResponseV1::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .kaikosdk.CantonOracleDataV1 data = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_data(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .kaikosdk.CantonOraclePayloadV1 canton_oracle = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_canton_oracle(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* StreamCantonOracleServiceResponseV1::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:kaikosdk.StreamCantonOracleServiceResponseV1)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .kaikosdk.CantonOracleDataV1 data = 1;
  if (this->_internal_has_data()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::data(this),
        _Internal::data(this).GetCachedSize(), target, stream);
  }

  // .kaikosdk.CantonOraclePayloadV1 canton_oracle = 2;
  if (this->_internal_has_canton_oracle()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::canton_oracle(this),
        _Internal::canton_oracle(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:kaikosdk.StreamCantonOracleServiceResponseV1)
  return target;
}

size_t StreamCantonOracleServiceResponseV1::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:kaikosdk.StreamCantonOracleServiceResponseV1)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .kaikosdk.CantonOracleDataV1 data = 1;
  if (this->_internal_has_data()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.data_);
  }

  // .kaikosdk.CantonOraclePayloadV1 canton_oracle = 2;
  if (this->_internal_has_canton_oracle()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.canton_oracle_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData StreamCantonOracleServiceResponseV1::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    StreamCantonOracleServiceResponseV1::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*StreamCantonOracleServiceResponseV1::GetClassData() const { return &_class_data_; }


void StreamCantonOracleServiceResponseV1::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<StreamCantonOracleServiceResponseV1*>(&to_msg);
  auto& from = static_cast<const StreamCantonOracleServiceResponseV1&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:kaikosdk.StreamCantonOracleServiceResponseV1)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_data()) {
    _this->_internal_mutable_data()->::kaikosdk::CantonOracleDataV1::MergeFrom(
        from._internal_data());
  }
  if (from._internal_has_canton_oracle()) {
    _this->_internal_mutable_canton_oracle()->::kaikosdk::CantonOraclePayloadV1::MergeFrom(
        from._internal_canton_oracle());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void StreamCantonOracleServiceResponseV1::CopyFrom(const StreamCantonOracleServiceResponseV1& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:kaikosdk.StreamCantonOracleServiceResponseV1)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StreamCantonOracleServiceResponseV1::IsInitialized() const {
  return true;
}

void StreamCantonOracleServiceResponseV1::InternalSwap(StreamCantonOracleServiceResponseV1* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(StreamCantonOracleServiceResponseV1, _impl_.canton_oracle_)
      + sizeof(StreamCantonOracleServiceResponseV1::_impl_.canton_oracle_)
      - PROTOBUF_FIELD_OFFSET(StreamCantonOracleServiceResponseV1, _impl_.data_)>(
          reinterpret_cast<char*>(&_impl_.data_),
          reinterpret_cast<char*>(&other->_impl_.data_));
}

::PROTOBUF_NAMESPACE_ID::Metadata StreamCantonOracleServiceResponseV1::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_sdk_2fstream_2fcanton_5foracle_5fv1_2fresponse_2eproto_getter, &descriptor_table_sdk_2fstream_2fcanton_5foracle_5fv1_2fresponse_2eproto_once,
      file_level_metadata_sdk_2fstream_2fcanton_5foracle_5fv1_2fresponse_2eproto[0]);
}

// ===================================================================

class CantonOracleDataV1::_Internal {
 public:
  using HasBits = decltype(std::declval<CantonOracleDataV1>()._impl_._has_bits_);
  static void set_has_value(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

CantonOracleDataV1::CantonOracleDataV1(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:kaikosdk.CantonOracleDataV1)
}
CantonOracleDataV1::CantonOracleDataV1(const CantonOracleDataV1& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CantonOracleDataV1* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.name_){}
    , decltype(_impl_.signature_){}
    , decltype(_impl_.value_){}
    , decltype(_impl_.timestamp_){}
    , decltype(_impl_.decimal_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_name().empty()) {
    _this->_impl_.name_.Set(from._internal_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.signature_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.signature_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_signature().empty()) {
    _this->_impl_.signature_.Set(from._internal_signature(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.value_, &from._impl_.value_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.decimal_) -
    reinterpret_cast<char*>(&_impl_.value_)) + sizeof(_impl_.decimal_));
  // @@protoc_insertion_point(copy_constructor:kaikosdk.CantonOracleDataV1)
}

inline void CantonOracleDataV1::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.name_){}
    , decltype(_impl_.signature_){}
    , decltype(_impl_.value_){int64_t{0}}
    , decltype(_impl_.timestamp_){int64_t{0}}
    , decltype(_impl_.decimal_){0}
  };
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.signature_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.signature_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

CantonOracleDataV1::~CantonOracleDataV1() {
  // @@protoc_insertion_point(destructor:kaikosdk.CantonOracleDataV1)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CantonOracleDataV1::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.name_.Destroy();
  _impl_.signature_.Destroy();
}

void CantonOracleDataV1::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CantonOracleDataV1::Clear() {
// @@protoc_insertion_point(message_clear_start:kaikosdk.CantonOracleDataV1)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  _impl_.signature_.ClearToEmpty();
  _impl_.value_ = int64_t{0};
  ::memset(&_impl_.timestamp_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.decimal_) -
      reinterpret_cast<char*>(&_impl_.timestamp_)) + sizeof(_impl_.decimal_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CantonOracleDataV1::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "kaikosdk.CantonOracleDataV1.name"));
        } else
          goto handle_unusual;
        continue;
      // optional int64 value = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _Internal::set_has_value(&has_bits);
          _impl_.value_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 decimal = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.decimal_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 timestamp = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.timestamp_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string signature = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_signature();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "kaikosdk.CantonOracleDataV1.signature"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CantonOracleDataV1::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:kaikosdk.CantonOracleDataV1)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "kaikosdk.CantonOracleDataV1.name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_name(), target);
  }

  // optional int64 value = 2;
  if (_internal_has_value()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(2, this->_internal_value(), target);
  }

  // int32 decimal = 3;
  if (this->_internal_decimal() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_decimal(), target);
  }

  // int64 timestamp = 4;
  if (this->_internal_timestamp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(4, this->_internal_timestamp(), target);
  }

  // string signature = 5;
  if (!this->_internal_signature().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_signature().data(), static_cast<int>(this->_internal_signature().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "kaikosdk.CantonOracleDataV1.signature");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_signature(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:kaikosdk.CantonOracleDataV1)
  return target;
}

size_t CantonOracleDataV1::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:kaikosdk.CantonOracleDataV1)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // string signature = 5;
  if (!this->_internal_signature().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_signature());
  }

  // optional int64 value = 2;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_value());
  }

  // int64 timestamp = 4;
  if (this->_internal_timestamp() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_timestamp());
  }

  // int32 decimal = 3;
  if (this->_internal_decimal() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_decimal());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CantonOracleDataV1::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CantonOracleDataV1::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CantonOracleDataV1::GetClassData() const { return &_class_data_; }


void CantonOracleDataV1::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CantonOracleDataV1*>(&to_msg);
  auto& from = static_cast<const CantonOracleDataV1&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:kaikosdk.CantonOracleDataV1)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (!from._internal_signature().empty()) {
    _this->_internal_set_signature(from._internal_signature());
  }
  if (from._internal_has_value()) {
    _this->_internal_set_value(from._internal_value());
  }
  if (from._internal_timestamp() != 0) {
    _this->_internal_set_timestamp(from._internal_timestamp());
  }
  if (from._internal_decimal() != 0) {
    _this->_internal_set_decimal(from._internal_decimal());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CantonOracleDataV1::CopyFrom(const CantonOracleDataV1& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:kaikosdk.CantonOracleDataV1)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CantonOracleDataV1::IsInitialized() const {
  return true;
}

void CantonOracleDataV1::InternalSwap(CantonOracleDataV1* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.name_, lhs_arena,
      &other->_impl_.name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.signature_, lhs_arena,
      &other->_impl_.signature_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CantonOracleDataV1, _impl_.decimal_)
      + sizeof(CantonOracleDataV1::_impl_.decimal_)
      - PROTOBUF_FIELD_OFFSET(CantonOracleDataV1, _impl_.value_)>(
          reinterpret_cast<char*>(&_impl_.value_),
          reinterpret_cast<char*>(&other->_impl_.value_));
}

::PROTOBUF_NAMESPACE_ID::Metadata CantonOracleDataV1::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_sdk_2fstream_2fcanton_5foracle_5fv1_2fresponse_2eproto_getter, &descriptor_table_sdk_2fstream_2fcanton_5foracle_5fv1_2fresponse_2eproto_once,
      file_level_metadata_sdk_2fstream_2fcanton_5foracle_5fv1_2fresponse_2eproto[1]);
}

// ===================================================================

class CantonOraclePayloadV1::_Internal {
 public:
};

CantonOraclePayloadV1::CantonOraclePayloadV1(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:kaikosdk.CantonOraclePayloadV1)
}
CantonOraclePayloadV1::CantonOraclePayloadV1(const CantonOraclePayloadV1& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CantonOraclePayloadV1* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.template_id_){}
    , decltype(_impl_.contract_id_){}
    , decltype(_impl_.synchronizer_id_){}
    , decltype(_impl_.created_event_blob_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.template_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.template_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_template_id().empty()) {
    _this->_impl_.template_id_.Set(from._internal_template_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.contract_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.contract_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_contract_id().empty()) {
    _this->_impl_.contract_id_.Set(from._internal_contract_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.synchronizer_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.synchronizer_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_synchronizer_id().empty()) {
    _this->_impl_.synchronizer_id_.Set(from._internal_synchronizer_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.created_event_blob_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.created_event_blob_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_created_event_blob().empty()) {
    _this->_impl_.created_event_blob_.Set(from._internal_created_event_blob(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:kaikosdk.CantonOraclePayloadV1)
}

inline void CantonOraclePayloadV1::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.template_id_){}
    , decltype(_impl_.contract_id_){}
    , decltype(_impl_.synchronizer_id_){}
    , decltype(_impl_.created_event_blob_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.template_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.template_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.contract_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.contract_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.synchronizer_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.synchronizer_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.created_event_blob_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.created_event_blob_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

CantonOraclePayloadV1::~CantonOraclePayloadV1() {
  // @@protoc_insertion_point(destructor:kaikosdk.CantonOraclePayloadV1)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CantonOraclePayloadV1::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.template_id_.Destroy();
  _impl_.contract_id_.Destroy();
  _impl_.synchronizer_id_.Destroy();
  _impl_.created_event_blob_.Destroy();
}

void CantonOraclePayloadV1::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CantonOraclePayloadV1::Clear() {
// @@protoc_insertion_point(message_clear_start:kaikosdk.CantonOraclePayloadV1)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.template_id_.ClearToEmpty();
  _impl_.contract_id_.ClearToEmpty();
  _impl_.synchronizer_id_.ClearToEmpty();
  _impl_.created_event_blob_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CantonOraclePayloadV1::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string template_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_template_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "kaikosdk.CantonOraclePayloadV1.template_id"));
        } else
          goto handle_unusual;
        continue;
      // string contract_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_contract_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "kaikosdk.CantonOraclePayloadV1.contract_id"));
        } else
          goto handle_unusual;
        continue;
      // string synchronizer_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_synchronizer_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "kaikosdk.CantonOraclePayloadV1.synchronizer_id"));
        } else
          goto handle_unusual;
        continue;
      // string created_event_blob = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_created_event_blob();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "kaikosdk.CantonOraclePayloadV1.created_event_blob"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CantonOraclePayloadV1::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:kaikosdk.CantonOraclePayloadV1)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string template_id = 1;
  if (!this->_internal_template_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_template_id().data(), static_cast<int>(this->_internal_template_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "kaikosdk.CantonOraclePayloadV1.template_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_template_id(), target);
  }

  // string contract_id = 2;
  if (!this->_internal_contract_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_contract_id().data(), static_cast<int>(this->_internal_contract_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "kaikosdk.CantonOraclePayloadV1.contract_id");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_contract_id(), target);
  }

  // string synchronizer_id = 3;
  if (!this->_internal_synchronizer_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_synchronizer_id().data(), static_cast<int>(this->_internal_synchronizer_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "kaikosdk.CantonOraclePayloadV1.synchronizer_id");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_synchronizer_id(), target);
  }

  // string created_event_blob = 4;
  if (!this->_internal_created_event_blob().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_created_event_blob().data(), static_cast<int>(this->_internal_created_event_blob().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "kaikosdk.CantonOraclePayloadV1.created_event_blob");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_created_event_blob(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:kaikosdk.CantonOraclePayloadV1)
  return target;
}

size_t CantonOraclePayloadV1::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:kaikosdk.CantonOraclePayloadV1)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string template_id = 1;
  if (!this->_internal_template_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_template_id());
  }

  // string contract_id = 2;
  if (!this->_internal_contract_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_contract_id());
  }

  // string synchronizer_id = 3;
  if (!this->_internal_synchronizer_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_synchronizer_id());
  }

  // string created_event_blob = 4;
  if (!this->_internal_created_event_blob().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_created_event_blob());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CantonOraclePayloadV1::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CantonOraclePayloadV1::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CantonOraclePayloadV1::GetClassData() const { return &_class_data_; }


void CantonOraclePayloadV1::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CantonOraclePayloadV1*>(&to_msg);
  auto& from = static_cast<const CantonOraclePayloadV1&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:kaikosdk.CantonOraclePayloadV1)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_template_id().empty()) {
    _this->_internal_set_template_id(from._internal_template_id());
  }
  if (!from._internal_contract_id().empty()) {
    _this->_internal_set_contract_id(from._internal_contract_id());
  }
  if (!from._internal_synchronizer_id().empty()) {
    _this->_internal_set_synchronizer_id(from._internal_synchronizer_id());
  }
  if (!from._internal_created_event_blob().empty()) {
    _this->_internal_set_created_event_blob(from._internal_created_event_blob());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CantonOraclePayloadV1::CopyFrom(const CantonOraclePayloadV1& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:kaikosdk.CantonOraclePayloadV1)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CantonOraclePayloadV1::IsInitialized() const {
  return true;
}

void CantonOraclePayloadV1::InternalSwap(CantonOraclePayloadV1* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.template_id_, lhs_arena,
      &other->_impl_.template_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.contract_id_, lhs_arena,
      &other->_impl_.contract_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.synchronizer_id_, lhs_arena,
      &other->_impl_.synchronizer_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.created_event_blob_, lhs_arena,
      &other->_impl_.created_event_blob_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata CantonOraclePayloadV1::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_sdk_2fstream_2fcanton_5foracle_5fv1_2fresponse_2eproto_getter, &descriptor_table_sdk_2fstream_2fcanton_5foracle_5fv1_2fresponse_2eproto_once,
      file_level_metadata_sdk_2fstream_2fcanton_5foracle_5fv1_2fresponse_2eproto[2]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace kaikosdk
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::kaikosdk::StreamCantonOracleServiceResponseV1*
Arena::CreateMaybeMessage< ::kaikosdk::StreamCantonOracleServiceResponseV1 >(Arena* arena) {
  return Arena::CreateMessageInternal< ::kaikosdk::StreamCantonOracleServiceResponseV1 >(arena);
}
template<> PROTOBUF_NOINLINE ::kaikosdk::CantonOracleDataV1*
Arena::CreateMaybeMessage< ::kaikosdk::CantonOracleDataV1 >(Arena* arena) {
  return Arena::CreateMessageInternal< ::kaikosdk::CantonOracleDataV1 >(arena);
}
template<> PROTOBUF_NOINLINE ::kaikosdk::CantonOraclePayloadV1*
Arena::CreateMaybeMessage< ::kaikosdk::CantonOraclePayloadV1 >(Arena* arena) {
  return Arena::CreateMessageInternal< ::kaikosdk::CantonOraclePayloadV1 >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
