// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk/stream/aggregated_state_price_v1/response.proto

#include "sdk/stream/aggregated_state_price_v1/response.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace kaikosdk {
PROTOBUF_CONSTEXPR StreamAggregatedStatePriceResponseV1::StreamAggregatedStatePriceResponseV1(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.base_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.aggregated_price_usd_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.aggregated_price_lst_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.lst_quote_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.aggregated_market_depth_m1_usd_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.aggregated_market_depth_p1_usd_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.datetime_)*/nullptr
  , /*decltype(_impl_.ts_event_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct StreamAggregatedStatePriceResponseV1DefaultTypeInternal {
  PROTOBUF_CONSTEXPR StreamAggregatedStatePriceResponseV1DefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~StreamAggregatedStatePriceResponseV1DefaultTypeInternal() {}
  union {
    StreamAggregatedStatePriceResponseV1 _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StreamAggregatedStatePriceResponseV1DefaultTypeInternal _StreamAggregatedStatePriceResponseV1_default_instance_;
}  // namespace kaikosdk
static ::_pb::Metadata file_level_metadata_sdk_2fstream_2faggregated_5fstate_5fprice_5fv1_2fresponse_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_sdk_2fstream_2faggregated_5fstate_5fprice_5fv1_2fresponse_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_sdk_2fstream_2faggregated_5fstate_5fprice_5fv1_2fresponse_2eproto = nullptr;

const uint32_t TableStruct_sdk_2fstream_2faggregated_5fstate_5fprice_5fv1_2fresponse_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::kaikosdk::StreamAggregatedStatePriceResponseV1, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::kaikosdk::StreamAggregatedStatePriceResponseV1, _impl_.datetime_),
  PROTOBUF_FIELD_OFFSET(::kaikosdk::StreamAggregatedStatePriceResponseV1, _impl_.base_),
  PROTOBUF_FIELD_OFFSET(::kaikosdk::StreamAggregatedStatePriceResponseV1, _impl_.aggregated_price_usd_),
  PROTOBUF_FIELD_OFFSET(::kaikosdk::StreamAggregatedStatePriceResponseV1, _impl_.aggregated_price_lst_),
  PROTOBUF_FIELD_OFFSET(::kaikosdk::StreamAggregatedStatePriceResponseV1, _impl_.ts_event_),
  PROTOBUF_FIELD_OFFSET(::kaikosdk::StreamAggregatedStatePriceResponseV1, _impl_.lst_quote_),
  PROTOBUF_FIELD_OFFSET(::kaikosdk::StreamAggregatedStatePriceResponseV1, _impl_.aggregated_market_depth_m1_usd_),
  PROTOBUF_FIELD_OFFSET(::kaikosdk::StreamAggregatedStatePriceResponseV1, _impl_.aggregated_market_depth_p1_usd_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::kaikosdk::StreamAggregatedStatePriceResponseV1)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::kaikosdk::_StreamAggregatedStatePriceResponseV1_default_instance_._instance,
};

const char descriptor_table_protodef_sdk_2fstream_2faggregated_5fstate_5fprice_5fv1_2fresponse_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n3sdk/stream/aggregated_state_price_v1/r"
  "esponse.proto\022\010kaikosdk\032\037google/protobuf"
  "/timestamp.proto\"\257\002\n$StreamAggregatedSta"
  "tePriceResponseV1\022,\n\010datetime\030\001 \001(\0132\032.go"
  "ogle.protobuf.Timestamp\022\014\n\004base\030\002 \001(\t\022\034\n"
  "\024aggregated_price_usd\030\003 \001(\t\022\034\n\024aggregate"
  "d_price_lst\030\004 \001(\t\022,\n\010ts_event\030\005 \001(\0132\032.go"
  "ogle.protobuf.Timestamp\022\021\n\tlst_quote\030\006 \001"
  "(\t\022&\n\036aggregated_market_depth_m1_usd\030\007 \001"
  "(\t\022&\n\036aggregated_market_depth_p1_usd\030\010 \001"
  "(\tB\271\001\n.com.kaiko.sdk.stream.aggregated_s"
  "tate_price_v1P\001Z\\github.com/kaikodata/ka"
  "iko-go-sdk/stream/aggregated_state_price"
  "_v1;aggregated_state_price_v1\252\002&KaikoSdk"
  ".Stream.AggregatedStatePriceV1b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_sdk_2fstream_2faggregated_5fstate_5fprice_5fv1_2fresponse_2eproto_deps[1] = {
  &::descriptor_table_google_2fprotobuf_2ftimestamp_2eproto,
};
static ::_pbi::once_flag descriptor_table_sdk_2fstream_2faggregated_5fstate_5fprice_5fv1_2fresponse_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_sdk_2fstream_2faggregated_5fstate_5fprice_5fv1_2fresponse_2eproto = {
    false, false, 598, descriptor_table_protodef_sdk_2fstream_2faggregated_5fstate_5fprice_5fv1_2fresponse_2eproto,
    "sdk/stream/aggregated_state_price_v1/response.proto",
    &descriptor_table_sdk_2fstream_2faggregated_5fstate_5fprice_5fv1_2fresponse_2eproto_once, descriptor_table_sdk_2fstream_2faggregated_5fstate_5fprice_5fv1_2fresponse_2eproto_deps, 1, 1,
    schemas, file_default_instances, TableStruct_sdk_2fstream_2faggregated_5fstate_5fprice_5fv1_2fresponse_2eproto::offsets,
    file_level_metadata_sdk_2fstream_2faggregated_5fstate_5fprice_5fv1_2fresponse_2eproto, file_level_enum_descriptors_sdk_2fstream_2faggregated_5fstate_5fprice_5fv1_2fresponse_2eproto,
    file_level_service_descriptors_sdk_2fstream_2faggregated_5fstate_5fprice_5fv1_2fresponse_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_sdk_2fstream_2faggregated_5fstate_5fprice_5fv1_2fresponse_2eproto_getter() {
  return &descriptor_table_sdk_2fstream_2faggregated_5fstate_5fprice_5fv1_2fresponse_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_sdk_2fstream_2faggregated_5fstate_5fprice_5fv1_2fresponse_2eproto(&descriptor_table_sdk_2fstream_2faggregated_5fstate_5fprice_5fv1_2fresponse_2eproto);
namespace kaikosdk {

// ===================================================================

class StreamAggregatedStatePriceResponseV1::_Internal {
 public:
  static const ::PROTOBUF_NAMESPACE_ID::Timestamp& datetime(const StreamAggregatedStatePriceResponseV1* msg);
  static const ::PROTOBUF_NAMESPACE_ID::Timestamp& ts_event(const StreamAggregatedStatePriceResponseV1* msg);
};

const ::PROTOBUF_NAMESPACE_ID::Timestamp&
StreamAggregatedStatePriceResponseV1::_Internal::datetime(const StreamAggregatedStatePriceResponseV1* msg) {
  return *msg->_impl_.datetime_;
}
const ::PROTOBUF_NAMESPACE_ID::Timestamp&
StreamAggregatedStatePriceResponseV1::_Internal::ts_event(const StreamAggregatedStatePriceResponseV1* msg) {
  return *msg->_impl_.ts_event_;
}
void StreamAggregatedStatePriceResponseV1::clear_datetime() {
  if (GetArenaForAllocation() == nullptr && _impl_.datetime_ != nullptr) {
    delete _impl_.datetime_;
  }
  _impl_.datetime_ = nullptr;
}
void StreamAggregatedStatePriceResponseV1::clear_ts_event() {
  if (GetArenaForAllocation() == nullptr && _impl_.ts_event_ != nullptr) {
    delete _impl_.ts_event_;
  }
  _impl_.ts_event_ = nullptr;
}
StreamAggregatedStatePriceResponseV1::StreamAggregatedStatePriceResponseV1(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:kaikosdk.StreamAggregatedStatePriceResponseV1)
}
StreamAggregatedStatePriceResponseV1::StreamAggregatedStatePriceResponseV1(const StreamAggregatedStatePriceResponseV1& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  StreamAggregatedStatePriceResponseV1* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.base_){}
    , decltype(_impl_.aggregated_price_usd_){}
    , decltype(_impl_.aggregated_price_lst_){}
    , decltype(_impl_.lst_quote_){}
    , decltype(_impl_.aggregated_market_depth_m1_usd_){}
    , decltype(_impl_.aggregated_market_depth_p1_usd_){}
    , decltype(_impl_.datetime_){nullptr}
    , decltype(_impl_.ts_event_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.base_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.base_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_base().empty()) {
    _this->_impl_.base_.Set(from._internal_base(), 
      _this->GetArenaForAllocation());
  }
  _impl_.aggregated_price_usd_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.aggregated_price_usd_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_aggregated_price_usd().empty()) {
    _this->_impl_.aggregated_price_usd_.Set(from._internal_aggregated_price_usd(), 
      _this->GetArenaForAllocation());
  }
  _impl_.aggregated_price_lst_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.aggregated_price_lst_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_aggregated_price_lst().empty()) {
    _this->_impl_.aggregated_price_lst_.Set(from._internal_aggregated_price_lst(), 
      _this->GetArenaForAllocation());
  }
  _impl_.lst_quote_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.lst_quote_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_lst_quote().empty()) {
    _this->_impl_.lst_quote_.Set(from._internal_lst_quote(), 
      _this->GetArenaForAllocation());
  }
  _impl_.aggregated_market_depth_m1_usd_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.aggregated_market_depth_m1_usd_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_aggregated_market_depth_m1_usd().empty()) {
    _this->_impl_.aggregated_market_depth_m1_usd_.Set(from._internal_aggregated_market_depth_m1_usd(), 
      _this->GetArenaForAllocation());
  }
  _impl_.aggregated_market_depth_p1_usd_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.aggregated_market_depth_p1_usd_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_aggregated_market_depth_p1_usd().empty()) {
    _this->_impl_.aggregated_market_depth_p1_usd_.Set(from._internal_aggregated_market_depth_p1_usd(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_datetime()) {
    _this->_impl_.datetime_ = new ::PROTOBUF_NAMESPACE_ID::Timestamp(*from._impl_.datetime_);
  }
  if (from._internal_has_ts_event()) {
    _this->_impl_.ts_event_ = new ::PROTOBUF_NAMESPACE_ID::Timestamp(*from._impl_.ts_event_);
  }
  // @@protoc_insertion_point(copy_constructor:kaikosdk.StreamAggregatedStatePriceResponseV1)
}

inline void StreamAggregatedStatePriceResponseV1::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.base_){}
    , decltype(_impl_.aggregated_price_usd_){}
    , decltype(_impl_.aggregated_price_lst_){}
    , decltype(_impl_.lst_quote_){}
    , decltype(_impl_.aggregated_market_depth_m1_usd_){}
    , decltype(_impl_.aggregated_market_depth_p1_usd_){}
    , decltype(_impl_.datetime_){nullptr}
    , decltype(_impl_.ts_event_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.base_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.base_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.aggregated_price_usd_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.aggregated_price_usd_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.aggregated_price_lst_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.aggregated_price_lst_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.lst_quote_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.lst_quote_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.aggregated_market_depth_m1_usd_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.aggregated_market_depth_m1_usd_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.aggregated_market_depth_p1_usd_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.aggregated_market_depth_p1_usd_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

StreamAggregatedStatePriceResponseV1::~StreamAggregatedStatePriceResponseV1() {
  // @@protoc_insertion_point(destructor:kaikosdk.StreamAggregatedStatePriceResponseV1)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void StreamAggregatedStatePriceResponseV1::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.base_.Destroy();
  _impl_.aggregated_price_usd_.Destroy();
  _impl_.aggregated_price_lst_.Destroy();
  _impl_.lst_quote_.Destroy();
  _impl_.aggregated_market_depth_m1_usd_.Destroy();
  _impl_.aggregated_market_depth_p1_usd_.Destroy();
  if (this != internal_default_instance()) delete _impl_.datetime_;
  if (this != internal_default_instance()) delete _impl_.ts_event_;
}

void StreamAggregatedStatePriceResponseV1::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void StreamAggregatedStatePriceResponseV1::Clear() {
// @@protoc_insertion_point(message_clear_start:kaikosdk.StreamAggregatedStatePriceResponseV1)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.base_.ClearToEmpty();
  _impl_.aggregated_price_usd_.ClearToEmpty();
  _impl_.aggregated_price_lst_.ClearToEmpty();
  _impl_.lst_quote_.ClearToEmpty();
  _impl_.aggregated_market_depth_m1_usd_.ClearToEmpty();
  _impl_.aggregated_market_depth_p1_usd_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.datetime_ != nullptr) {
    delete _impl_.datetime_;
  }
  _impl_.datetime_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.ts_event_ != nullptr) {
    delete _impl_.ts_event_;
  }
  _impl_.ts_event_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* StreamAggregatedStatePriceResponseV1::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .google.protobuf.Timestamp datetime = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_datetime(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string base = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_base();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "kaikosdk.StreamAggregatedStatePriceResponseV1.base"));
        } else
          goto handle_unusual;
        continue;
      // string aggregated_price_usd = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_aggregated_price_usd();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "kaikosdk.StreamAggregatedStatePriceResponseV1.aggregated_price_usd"));
        } else
          goto handle_unusual;
        continue;
      // string aggregated_price_lst = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_aggregated_price_lst();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "kaikosdk.StreamAggregatedStatePriceResponseV1.aggregated_price_lst"));
        } else
          goto handle_unusual;
        continue;
      // .google.protobuf.Timestamp ts_event = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_ts_event(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string lst_quote = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          auto str = _internal_mutable_lst_quote();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "kaikosdk.StreamAggregatedStatePriceResponseV1.lst_quote"));
        } else
          goto handle_unusual;
        continue;
      // string aggregated_market_depth_m1_usd = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          auto str = _internal_mutable_aggregated_market_depth_m1_usd();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "kaikosdk.StreamAggregatedStatePriceResponseV1.aggregated_market_depth_m1_usd"));
        } else
          goto handle_unusual;
        continue;
      // string aggregated_market_depth_p1_usd = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          auto str = _internal_mutable_aggregated_market_depth_p1_usd();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "kaikosdk.StreamAggregatedStatePriceResponseV1.aggregated_market_depth_p1_usd"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* StreamAggregatedStatePriceResponseV1::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:kaikosdk.StreamAggregatedStatePriceResponseV1)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .google.protobuf.Timestamp datetime = 1;
  if (this->_internal_has_datetime()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::datetime(this),
        _Internal::datetime(this).GetCachedSize(), target, stream);
  }

  // string base = 2;
  if (!this->_internal_base().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_base().data(), static_cast<int>(this->_internal_base().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "kaikosdk.StreamAggregatedStatePriceResponseV1.base");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_base(), target);
  }

  // string aggregated_price_usd = 3;
  if (!this->_internal_aggregated_price_usd().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_aggregated_price_usd().data(), static_cast<int>(this->_internal_aggregated_price_usd().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "kaikosdk.StreamAggregatedStatePriceResponseV1.aggregated_price_usd");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_aggregated_price_usd(), target);
  }

  // string aggregated_price_lst = 4;
  if (!this->_internal_aggregated_price_lst().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_aggregated_price_lst().data(), static_cast<int>(this->_internal_aggregated_price_lst().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "kaikosdk.StreamAggregatedStatePriceResponseV1.aggregated_price_lst");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_aggregated_price_lst(), target);
  }

  // .google.protobuf.Timestamp ts_event = 5;
  if (this->_internal_has_ts_event()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::ts_event(this),
        _Internal::ts_event(this).GetCachedSize(), target, stream);
  }

  // string lst_quote = 6;
  if (!this->_internal_lst_quote().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_lst_quote().data(), static_cast<int>(this->_internal_lst_quote().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "kaikosdk.StreamAggregatedStatePriceResponseV1.lst_quote");
    target = stream->WriteStringMaybeAliased(
        6, this->_internal_lst_quote(), target);
  }

  // string aggregated_market_depth_m1_usd = 7;
  if (!this->_internal_aggregated_market_depth_m1_usd().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_aggregated_market_depth_m1_usd().data(), static_cast<int>(this->_internal_aggregated_market_depth_m1_usd().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "kaikosdk.StreamAggregatedStatePriceResponseV1.aggregated_market_depth_m1_usd");
    target = stream->WriteStringMaybeAliased(
        7, this->_internal_aggregated_market_depth_m1_usd(), target);
  }

  // string aggregated_market_depth_p1_usd = 8;
  if (!this->_internal_aggregated_market_depth_p1_usd().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_aggregated_market_depth_p1_usd().data(), static_cast<int>(this->_internal_aggregated_market_depth_p1_usd().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "kaikosdk.StreamAggregatedStatePriceResponseV1.aggregated_market_depth_p1_usd");
    target = stream->WriteStringMaybeAliased(
        8, this->_internal_aggregated_market_depth_p1_usd(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:kaikosdk.StreamAggregatedStatePriceResponseV1)
  return target;
}

size_t StreamAggregatedStatePriceResponseV1::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:kaikosdk.StreamAggregatedStatePriceResponseV1)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string base = 2;
  if (!this->_internal_base().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_base());
  }

  // string aggregated_price_usd = 3;
  if (!this->_internal_aggregated_price_usd().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_aggregated_price_usd());
  }

  // string aggregated_price_lst = 4;
  if (!this->_internal_aggregated_price_lst().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_aggregated_price_lst());
  }

  // string lst_quote = 6;
  if (!this->_internal_lst_quote().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_lst_quote());
  }

  // string aggregated_market_depth_m1_usd = 7;
  if (!this->_internal_aggregated_market_depth_m1_usd().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_aggregated_market_depth_m1_usd());
  }

  // string aggregated_market_depth_p1_usd = 8;
  if (!this->_internal_aggregated_market_depth_p1_usd().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_aggregated_market_depth_p1_usd());
  }

  // .google.protobuf.Timestamp datetime = 1;
  if (this->_internal_has_datetime()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.datetime_);
  }

  // .google.protobuf.Timestamp ts_event = 5;
  if (this->_internal_has_ts_event()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.ts_event_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData StreamAggregatedStatePriceResponseV1::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    StreamAggregatedStatePriceResponseV1::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*StreamAggregatedStatePriceResponseV1::GetClassData() const { return &_class_data_; }


void StreamAggregatedStatePriceResponseV1::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<StreamAggregatedStatePriceResponseV1*>(&to_msg);
  auto& from = static_cast<const StreamAggregatedStatePriceResponseV1&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:kaikosdk.StreamAggregatedStatePriceResponseV1)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_base().empty()) {
    _this->_internal_set_base(from._internal_base());
  }
  if (!from._internal_aggregated_price_usd().empty()) {
    _this->_internal_set_aggregated_price_usd(from._internal_aggregated_price_usd());
  }
  if (!from._internal_aggregated_price_lst().empty()) {
    _this->_internal_set_aggregated_price_lst(from._internal_aggregated_price_lst());
  }
  if (!from._internal_lst_quote().empty()) {
    _this->_internal_set_lst_quote(from._internal_lst_quote());
  }
  if (!from._internal_aggregated_market_depth_m1_usd().empty()) {
    _this->_internal_set_aggregated_market_depth_m1_usd(from._internal_aggregated_market_depth_m1_usd());
  }
  if (!from._internal_aggregated_market_depth_p1_usd().empty()) {
    _this->_internal_set_aggregated_market_depth_p1_usd(from._internal_aggregated_market_depth_p1_usd());
  }
  if (from._internal_has_datetime()) {
    _this->_internal_mutable_datetime()->::PROTOBUF_NAMESPACE_ID::Timestamp::MergeFrom(
        from._internal_datetime());
  }
  if (from._internal_has_ts_event()) {
    _this->_internal_mutable_ts_event()->::PROTOBUF_NAMESPACE_ID::Timestamp::MergeFrom(
        from._internal_ts_event());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void StreamAggregatedStatePriceResponseV1::CopyFrom(const StreamAggregatedStatePriceResponseV1& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:kaikosdk.StreamAggregatedStatePriceResponseV1)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StreamAggregatedStatePriceResponseV1::IsInitialized() const {
  return true;
}

void StreamAggregatedStatePriceResponseV1::InternalSwap(StreamAggregatedStatePriceResponseV1* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.base_, lhs_arena,
      &other->_impl_.base_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.aggregated_price_usd_, lhs_arena,
      &other->_impl_.aggregated_price_usd_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.aggregated_price_lst_, lhs_arena,
      &other->_impl_.aggregated_price_lst_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.lst_quote_, lhs_arena,
      &other->_impl_.lst_quote_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.aggregated_market_depth_m1_usd_, lhs_arena,
      &other->_impl_.aggregated_market_depth_m1_usd_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.aggregated_market_depth_p1_usd_, lhs_arena,
      &other->_impl_.aggregated_market_depth_p1_usd_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(StreamAggregatedStatePriceResponseV1, _impl_.ts_event_)
      + sizeof(StreamAggregatedStatePriceResponseV1::_impl_.ts_event_)
      - PROTOBUF_FIELD_OFFSET(StreamAggregatedStatePriceResponseV1, _impl_.datetime_)>(
          reinterpret_cast<char*>(&_impl_.datetime_),
          reinterpret_cast<char*>(&other->_impl_.datetime_));
}

::PROTOBUF_NAMESPACE_ID::Metadata StreamAggregatedStatePriceResponseV1::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_sdk_2fstream_2faggregated_5fstate_5fprice_5fv1_2fresponse_2eproto_getter, &descriptor_table_sdk_2fstream_2faggregated_5fstate_5fprice_5fv1_2fresponse_2eproto_once,
      file_level_metadata_sdk_2fstream_2faggregated_5fstate_5fprice_5fv1_2fresponse_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace kaikosdk
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::kaikosdk::StreamAggregatedStatePriceResponseV1*
Arena::CreateMaybeMessage< ::kaikosdk::StreamAggregatedStatePriceResponseV1 >(Arena* arena) {
  return Arena::CreateMessageInternal< ::kaikosdk::StreamAggregatedStatePriceResponseV1 >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
